/**
 * BL Renovations — site content data.
 * Auto-generated by Content Architect. Do not edit manually.
 * Re-generated on each pipeline build.
 */

export const SITE_ID = "bl-renovations";

export const PUBLIC_CONTENT = {
  "heroEyebrow": "FAMILY-OWNED AND LOCALLY OPERATED",
  "heroHeadline": "Welcome Home",
  "heroSubheadline": "Family-Owned and Locally Operated",
  "heroPrimaryCta": {
    "label": "Book Your Free In-Home Consultation",
    "href": "/visualizer"
  },
  "heroSecondaryCta": {
    "label": "Request Your Personalized Estimate",
    "href": "/visualizer?mode=chat"
  },
  "businessHistory": "BL Renovations presents itself as a family-owned and locally operated renovation company serving Owen Sound and Grey Bruce. The company emphasizes friendly, personalized service, free in-home consultations, and in-house project management from demolition through finishing details. Its approach centers on helping homeowners find products and solutions that match their style, budget, and project needs."
} as const;

export const SERVICES = [
  {
    "name": "Kitchen Remodels",
    "slug": "kitchen-remodels",
    "description": "BL Renovations offers kitchen remodels backed by friendly, personalized service and free in-home consultations. The company helps homeowners choose products and solutions that fit their style, budget, and project goals, then manages each phase in-house from demolition through finishing details. That start-to-finish approach is designed to save clients time while keeping the project organized and efficient.",
    "shortDescription": "Custom kitchen remodels with in-home consultations, personalized product guidance, and in-house project management from start to finish.",
    "features": [
      "Free in-home consultation and precise measurements",
      "Personalized guidance on products and solutions",
      "Custom planning around style, budget, and project needs",
      "In-house management from demo to decor",
      "Timeline and schedule updates as work progresses",
      "High-end custom solutions with a budget-friendly approach"
    ],
    "faqs": [
      {
        "question": "Do you offer in-home consultations for kitchen remodels?",
        "answer": "Yes. BL Renovations offers free in-home consultations so measurements can be taken accurately and the project can be discussed in person."
      },
      {
        "question": "Can you help me choose products that fit my style and budget?",
        "answer": "Yes. The company says it helps clients find the right products and solutions to match their style, budget, and project needs."
      },
      {
        "question": "Do you manage the whole kitchen renovation or just parts of it?",
        "answer": "BL Renovations states that it manages every aspect of the project from start to finish in-house, from demo to decor."
      },
      {
        "question": "How do I book my kitchen renovation?",
        "answer": "After the in-home visit and estimate, a 10% deposit is required to secure the booking and collect any special materials needed for the project."
      },
      {
        "question": "Will I know when my kitchen project is scheduled to start?",
        "answer": "Yes. BL Renovations says it updates prospective clients on timelines and schedules as projects progress to ensure accurate start times."
      }
    ],
    "pageEyebrow": "Welcome Home",
    "pageTitle": "Kitchen Remodels"
  },
  {
    "name": "Bathroom Renovations",
    "slug": "bathroom-renovations",
    "description": "BL Renovations provides bathroom renovation services with the personalized attention of a family-owned, locally operated business. Homeowners can begin with a free in-home consultation, then work through product and solution choices that suit their style, budget, and renovation goals. The company manages the project in-house from start to finish, helping streamline the process and keep communication clear.",
    "shortDescription": "Bathroom renovations planned around your style and budget, with free in-home consultations and in-house project management.",
    "features": [
      "Free in-home consultation with precise measurements",
      "Personalized service from a family-owned local company",
      "Product and solution guidance tailored to the project",
      "In-house management from demolition to finishing details",
      "Fast and efficient scheduling updates",
      "Custom renovation planning with budget-conscious options"
    ],
    "faqs": [
      {
        "question": "Do you provide free estimates for bathroom renovations?",
        "answer": "Yes. The process starts with a free in-home consultation, followed by a personalized and detailed quote based on the information gathered during the visit."
      },
      {
        "question": "Can you help me decide what products are right for my bathroom?",
        "answer": "Yes. BL Renovations says it helps clients find the right products and solutions that match their style, budget, and project needs."
      },
      {
        "question": "Is the renovation handled by one company from start to finish?",
        "answer": "Yes. BL Renovations says it manages every aspect of the project in-house from start to finish."
      },
      {
        "question": "What deposit is required to book a bathroom renovation?",
        "answer": "The company requires a 10% deposit to secure the booking and collect any special materials needed for the project."
      },
      {
        "question": "Will I receive timeline updates during the renovation?",
        "answer": "Yes. BL Renovations says it updates prospective clients on timelines and schedules as projects progress."
      }
    ],
    "pageEyebrow": "Welcome Home",
    "pageTitle": "Bathroom Renovations"
  },
  {
    "name": "Basement Finishing",
    "slug": "basement-finishing",
    "description": "BL Renovations offers basement finishing services with a focus on personalized service and practical planning. Through a free in-home consultation, the company gathers measurements and project details so it can recommend products and solutions that align with the homeowner's style, budget, and needs. Work is managed in-house from start to finish to save time and keep the project moving efficiently.",
    "shortDescription": "Basement finishing services supported by free in-home consultations, tailored planning, and start-to-finish in-house management.",
    "features": [
      "Free in-home consultation and site measurement",
      "Project planning around style, budget, and functional needs",
      "Guidance on suitable products and finishing solutions",
      "In-house management from demo through completion",
      "Clear scheduling and timeline communication",
      "Locally operated service with a personal touch"
    ],
    "faqs": [
      {
        "question": "How do you start a basement finishing project?",
        "answer": "The process starts with a free in-home consultation where BL Renovations can take precise measurements and discuss the project in detail."
      },
      {
        "question": "Will the quote be specific to my basement?",
        "answer": "Yes. The company prepares a personalized and detailed quote based on the information gathered during the in-home visit."
      },
      {
        "question": "Can the project be tailored to my budget?",
        "answer": "Yes. BL Renovations says it helps homeowners find solutions that match their style, budget, and project needs."
      },
      {
        "question": "Do you coordinate the work in-house?",
        "answer": "Yes. BL Renovations says it manages every aspect from start to finish in-house."
      },
      {
        "question": "What is required to secure the booking?",
        "answer": "A 10% deposit is required to secure the booking and arrange for any special materials needed for the project."
      }
    ],
    "pageEyebrow": "Welcome Home",
    "pageTitle": "Basement Finishing"
  },
  {
    "name": "Flooring & Tile Installations",
    "slug": "flooring-and-tile-installations",
    "description": "BL Renovations provides flooring and tile installation services with personalized support from consultation through completion. Free in-home visits allow the team to take precise measurements and help clients choose products and solutions that fit their style, budget, and project needs. Because the work is managed in-house, homeowners get a more coordinated process with ongoing schedule updates along the way.",
    "shortDescription": "Flooring and tile installations with precise in-home measurements, product guidance, and in-house project coordination.",
    "features": [
      "Free in-home consultation with precise measurements",
      "Product selection support based on style and budget",
      "In-house project management from start to finish",
      "Fast and efficient scheduling communication",
      "Custom solutions for renovation needs",
      "Locally operated, personalized client service"
    ],
    "faqs": [
      {
        "question": "Do you come to the home before preparing a flooring or tile quote?",
        "answer": "Yes. BL Renovations offers free in-home consultations so measurements can be taken accurately before preparing a detailed quote."
      },
      {
        "question": "Can you help me choose the right flooring or tile for my project?",
        "answer": "Yes. The company says it helps clients find the right products and solutions to suit their style, budget, and project needs."
      },
      {
        "question": "Is the installation work handled in-house?",
        "answer": "Yes. BL Renovations says it manages projects in-house from start to finish."
      },
      {
        "question": "How do I reserve a spot on your schedule?",
        "answer": "Once you are ready to move forward, a 10% deposit secures the booking and covers any special materials needed for the project."
      },
      {
        "question": "Will I receive updates on timing?",
        "answer": "Yes. BL Renovations says it keeps clients informed on timelines and schedules as projects progress."
      }
    ],
    "pageEyebrow": "Welcome Home",
    "pageTitle": "Flooring & Tile Installations"
  },
  {
    "name": "Fixture Installations",
    "slug": "fixture-installations",
    "description": "BL Renovations offers fixture installation services as part of its personalized, start-to-finish renovation support. Homeowners can arrange a free in-home consultation to review the project, get precise measurements where needed, and discuss products and solutions that fit the space, style, and budget. With in-house project management and clear scheduling communication, the company aims to make installation work straightforward and efficient.",
    "shortDescription": "Fixture installations backed by free in-home consultations, tailored recommendations, and clear in-house coordination.",
    "features": [
      "Free in-home consultation and project review",
      "Guidance on products and solutions that fit the space",
      "Precise measurements with a personal touch",
      "In-house coordination from booking through installation",
      "Timeline and schedule updates during the project",
      "Budget-friendly service from a locally operated business"
    ],
    "faqs": [
      {
        "question": "Do you offer consultations before fixture installation work begins?",
        "answer": "Yes. BL Renovations offers free in-home consultations so the work can be reviewed and the right solutions can be discussed."
      },
      {
        "question": "Can you help me select fixtures that suit my project?",
        "answer": "Yes. The company says it helps clients find the right products and solutions based on their style, budget, and project needs."
      },
      {
        "question": "How is the project quoted?",
        "answer": "After the in-home visit, BL Renovations prepares a personalized and detailed quote based on the information gathered."
      },
      {
        "question": "What is needed to confirm the booking?",
        "answer": "A 10% deposit is required to secure the booking and collect any special materials needed for the job."
      },
      {
        "question": "Do you keep clients updated on scheduling?",
        "answer": "Yes. BL Renovations says it provides timeline and schedule updates as projects progress."
      }
    ],
    "pageEyebrow": "Welcome Home",
    "pageTitle": "Fixture Installations"
  }
] as const;

export const TESTIMONIALS = [] as const;

export const PROJECTS = [] as const;

export const TEAM_MEMBERS = [] as const;

export const PRINCIPALS = [] as const;

export const SERVICE_AREAS = [
  "Owen Sound",
  "Grey Bruce"
] as const;

export const PROCESS_STEPS = [
  {
    "title": "Contact",
    "description": "We focus on our customers to help them find the options that best suit their needs; that’s why we offer free in-home consultations to assist you in making an informed decision."
  },
  {
    "title": "Estimate",
    "description": "Based on the information we gather during your in-home visit, we will prepare a personalized and detailed quote just for you."
  },
  {
    "title": "Book",
    "description": "When you're ready to move forward, we only require a 10% deposit to secure your booking and to collect any special materials we may need for the project."
  },
  {
    "title": "Install",
    "description": "We update prospective clients on timelines and schedules as projects progress to ensure accurate start times."
  }
] as const;

export const TRUST_METRICS = {
  "yearsInBusiness": null,
  "projectsCompleted": null,
  "googleRating": null,
  "googleReviewCount": null,
  "certifications": [
    "Commercially Bonded",
    "Insured"
  ],
  "awards": []
} as const;

export const FAQ_ITEMS = [
  {
    "question": "What areas does BL Renovations serve?",
    "answer": "BL Renovations serves Owen Sound and Grey Bruce."
  },
  {
    "question": "What kind of consultations do you offer?",
    "answer": "The company offers free in-home consultations so clients can discuss their project, get precise measurements, and make informed decisions."
  },
  {
    "question": "How are quotes prepared?",
    "answer": "After the in-home visit, BL Renovations prepares a personalized and detailed quote based on the information gathered during the consultation."
  },
  {
    "question": "What deposit is required to book a project?",
    "answer": "A 10% deposit is required to secure the booking and collect any special materials needed for the project."
  },
  {
    "question": "How does BL Renovations manage projects?",
    "answer": "BL Renovations says it manages every aspect from start to finish in-house, helping save clients time and money."
  },
  {
    "question": "Will I get updates on project timing?",
    "answer": "Yes. The company says it updates prospective clients on timelines and schedules as projects progress."
  }
] as const;

export const CONTACT = {
  "phone": "519.379.8995",
  "email": "info@blrenos.ca",
  "address": null,
  "hours": null,
  "socialLinks": []
} as const;
