/**
 * CCR Renovations — site content data.
 * Auto-generated by Content Architect. Do not edit manually.
 * Re-generated on each pipeline build.
 */

export const SITE_ID = "ccr-renovations";

export const PUBLIC_CONTENT = {
  "heroEyebrow": "Renovation contractor in Durham Region, Ontario",
  "heroHeadline": "Specialists in All Aspects of Durham Home Renovations and Remodeling",
  "heroSubheadline": "Excellence. Integrity. Dependability.",
  "heroPrimaryCta": {
    "label": "Get Your Free Design Estimate",
    "href": "/visualizer"
  },
  "heroSecondaryCta": {
    "label": "See Your Space Before You Build",
    "href": "/visualizer?mode=chat"
  },
  "businessHistory": null
} as const;

export const SERVICES = [
  {
    "name": "Basements",
    "slug": "basements",
    "description": "A finished basement/conversion will transform your living space and the way you use your entire home.",
    "shortDescription": "A finished basement/conversion will transform your living space and the way you use your entire home",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Kitchens",
    "slug": "kitchens",
    "description": "We will assist in every aspect of your project, working alongside bespoke cabinetry companies, to tailor-make your dream kitchen.",
    "shortDescription": "We will assist in every aspect of your project, working alongside bespoke cabinetry companies, to ta",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Bathrooms",
    "slug": "bathrooms",
    "description": "Whether you are looking to renovate your existing bathroom or create a new space in a basement or new build, CCR Renovations can oblige.",
    "shortDescription": "Whether you are looking to renovate your existing bathroom or create a new space in a basement or ne",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Decks",
    "slug": "decks",
    "description": "From the smallest yard project to a large landscaped theme with a custom 2 storey deck, we can help you convert your ideas into reality.",
    "shortDescription": "From the smallest yard project to a large landscaped theme with a custom 2 storey deck, we can help ",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Home Additions",
    "slug": "home-additions",
    "description": "CCR Renovations know that extra room(s) will not only maximise the enjoyment of your home for you and your family, but will also unlock its hidden potential.",
    "shortDescription": "CCR Renovations know that extra room(s) will not only maximise the enjoyment of your home for you an",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  }
] as const;

export const TESTIMONIALS = [
  {
    "author": "Sonia, Toronto",
    "text": "Thank you to CCR Renovations for totally executing my vision to a T. There was nothing CCR wouldn't do to make sure the stain on the stairs was Perfect!",
    "rating": 5,
    "source": null
  },
  {
    "author": "Steve, Whitby",
    "text": "CCR Renovations did an outstanding job, paying particular attention to detail and quality of material and workmanship. The end product was simply AWESOME.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Syd & Amanda, Oshawa",
    "text": "The bathroom is everything we wanted from the very beginning, and we couldn't be happier. We wouldn't think twice about hiring CCR for future projects.",
    "rating": 5,
    "source": null
  }
] as const;

export const PROJECTS = [
  {
    "title": "Melissa and Steve's Eclectic, Bold & Beautiful Main Floor!",
    "description": "CCR Renovations is excited to share with you our recent bold renovation!",
    "category": null
  },
  {
    "title": "Arielle & Sean's Exceptional Whitby Backsplit",
    "description": "CCR Renovations is delighted to share their most recent finished project!",
    "category": null
  },
  {
    "title": "Mel & Andrew's Brooklin Beauty",
    "description": "CCR Renovations are proud to present this substantial renovation project undertaken for an awesome Brooklin couple.",
    "category": null
  },
  {
    "title": "Mike & Virginia's Multi Level Home Showcase",
    "description": "CCR Renovations are proud to showcase this extensive home renovation project that we have recently completed.",
    "category": null
  },
  {
    "title": "Jiun & Bob's Whitby Main Floor Renovation",
    "description": "Our Whitby clients wanted to breathe new life into their dated kitchen and have a modern space.",
    "category": null
  },
  {
    "title": "Lynda & Craig's Blackstock Entire Home Renovation",
    "description": "CCR Renovations took on this mammoth task and completely transformed this home.",
    "category": null
  }
] as const;

export const TEAM_MEMBERS = [
  {
    "name": "Stuart",
    "role": "Founder/Site Foreman",
    "photo_url": "https://www.ccr-renovations.com/wp-content/uploads/sites/260/2025/03/STUART-NEW-WEBSITE-PHOTO.jpg",
    "bio": "As founder and site foreman of CCR Renovations, Stuart oversees every aspect of the construction side of our business."
  },
  {
    "name": "Matt",
    "role": "Sales Manager",
    "photo_url": "https://www.ccr-renovations.com/wp-content/uploads/sites/260/2025/03/MATT-NEW-WEBSITE-PHOTO-cropped.jpg",
    "bio": "Matt manages all aspects of project estimation; from the initial phone call to the signing date."
  },
  {
    "name": "Conor",
    "role": "Project Manager",
    "photo_url": "https://www.ccr-renovations.com/wp-content/uploads/sites/260/2025/03/CONOR-NEW-WEBSITE-PHOTO.jpg",
    "bio": "With an in-depth understanding of the industry and a hands-on background, Conor ensures each project is executed with precision from start to finish."
  },
  {
    "name": "Tara",
    "role": "Interior Design Coordinator",
    "photo_url": "https://www.ccr-renovations.com/wp-content/uploads/sites/260/2025/03/TARA-WEBSITE-PHOTO.jpg",
    "bio": "With a keen eye for aesthetics and years of project experience, Tara helps refine your style, offering direction on layouts, materials, and finishes."
  }
] as const;

export const PRINCIPALS = [] as const;

export const SERVICE_AREAS = [
  "Durham Region",
  "Ontario"
] as const;

export const PROCESS_STEPS = [
  {
    "title": "Initial Consultation",
    "description": "Discuss your project needs and expectations."
  },
  {
    "title": "Proposal and Estimates",
    "description": "Get detailed proposals and project cost estimates."
  },
  {
    "title": "Design Phase",
    "description": "Collaborate to finalize designs that meet your vision."
  },
  {
    "title": "Project Execution",
    "description": "Experienced teams carry out the renovation as planned."
  },
  {
    "title": "Project Review",
    "description": "Walk through the completed project and ensure satisfaction."
  }
] as const;

export const TRUST_METRICS = {
  "yearsInBusiness": null,
  "projectsCompleted": null,
  "googleRating": null,
  "googleReviewCount": null,
  "certifications": [
    "Public liability insurance",
    "WSIB coverage"
  ],
  "awards": []
} as const;

export const FAQ_ITEMS = [] as const;

export const CONTACT = {
  "phone": "(289) 675-7366",
  "email": "info@ccr-renovations.com",
  "address": "105-801 Lawrence Ave E",
  "hours": "Mon-Fri 8am-5pm",
  "socialLinks": []
} as const;
