/**
 * Go Hard Corporation — site content data.
 * Auto-generated by Content Architect. Do not edit manually.
 * Re-generated on each pipeline build.
 */

export const SITE_ID = "go-hard-corporation";

export const PUBLIC_CONTENT = {
  "heroEyebrow": "FULL HOME RENOVATIONS",
  "heroHeadline": "Full Home Renovations in Kitchener, Waterloo, Cambridge and Guelph",
  "heroSubheadline": "Creating beautiful bespoke and functional spaces.",
  "heroPrimaryCta": {
    "label": "Start Your Renovation",
    "href": "/visualizer"
  },
  "heroSecondaryCta": {
    "label": "Book a Consultation",
    "href": "/visualizer?mode=chat"
  },
  "businessHistory": "Go Hard Corporation is a full-service design-build renovation company serving Kitchener, Waterloo, Cambridge, and Guelph. The company specializes in kitchens, bathrooms, and home additions, handling projects from design and permits through construction with support from interior designers, project managers, and skilled builders. For nearly a decade, clients have trusted the team to create clean, functional, and beautiful spaces tailored to their lifestyle and personal style."
} as const;

export const SERVICES = [
  {
    "name": "Kitchen Renovation",
    "slug": "kitchen-renovation",
    "description": "Go Hard Corporation provides kitchen renovations designed to make the heart of the home more functional, beautiful, and tailored to daily life. As a full-service design-build company, the team supports homeowners from design and permits through construction, combining interior design guidance, project management, and skilled craftsmanship. Each kitchen is planned to reflect the homeowner's style while improving how the space looks, works, and feels.",
    "shortDescription": "Transform your kitchen into a functional and beautiful space with custom design-build renovation services.",
    "features": [
      "Custom kitchen designs",
      "High-quality materials",
      "Expert craftsmanship",
      "Design-build project delivery",
      "Permit coordination",
      "Interior design and project management support"
    ],
    "faqs": [
      {
        "question": "Do you offer custom kitchen designs?",
        "answer": "Yes. Go Hard Corporation highlights custom designs as part of its kitchen renovation service and works to create spaces that reflect your style and suit your lifestyle."
      },
      {
        "question": "Can you handle the kitchen project from start to finish?",
        "answer": "Yes. As a full-service design-build renovation company, the team manages the process from design and permits through construction."
      },
      {
        "question": "What makes your kitchen renovations functional as well as beautiful?",
        "answer": "The company focuses on creating kitchens that not only look stunning but also function well for everyday living, with careful attention to layout, materials, and craftsmanship."
      },
      {
        "question": "Who works on a kitchen renovation project?",
        "answer": "Projects are supported by interior designers, project managers, and skilled builders, giving homeowners guidance through both planning and construction."
      },
      {
        "question": "Do you use quality materials in kitchen renovations?",
        "answer": "Yes. High-quality materials are specifically listed as a feature of the company's kitchen renovation work."
      },
      {
        "question": "Do you serve homeowners outside Kitchener?",
        "answer": "Yes. Go Hard Corporation serves Kitchener, Waterloo, Cambridge, and Guelph."
      }
    ],
    "pageEyebrow": "FULL-SERVICE DESIGN-BUILD RENOVATIONS",
    "pageTitle": "Kitchen Renovation"
  },
  {
    "name": "Bathroom Renovation",
    "slug": "bathroom-renovation",
    "description": "Go Hard Corporation renovates bathrooms to improve both functionality and aesthetics, creating spaces that feel clean, personal, and complete. The team brings together tailored design, custom cabinetry, and modern fixtures to build bathrooms that suit the way homeowners live. From design and permits to construction, the company delivers a full-service renovation experience backed by skilled professionals.",
    "shortDescription": "Upgrade your bathroom with a design-build renovation focused on function, comfort, and style.",
    "features": [
      "Modern fixtures",
      "Custom cabinetry",
      "Space-saving designs",
      "Tailored bathroom layouts",
      "Design-build project management",
      "Construction from design through completion"
    ],
    "faqs": [
      {
        "question": "Can you redesign a bathroom to make better use of space?",
        "answer": "Yes. Space-saving designs are one of the listed features of Go Hard Corporation's bathroom renovation service."
      },
      {
        "question": "Do you offer custom cabinetry for bathrooms?",
        "answer": "Yes. Custom cabinetry is specifically included as part of the bathroom renovation offering."
      },
      {
        "question": "Will you help with the design of the new bathroom?",
        "answer": "Yes. The company is a full-service design-build renovator and works with interior designers, project managers, and builders to guide the process."
      },
      {
        "question": "Do you handle permits for bathroom renovations?",
        "answer": "Go Hard Corporation states that it manages projects from design and permits through the build, so permit coordination is part of its overall renovation process where required."
      },
      {
        "question": "What kind of bathroom style do you build?",
        "answer": "The team creates bathrooms that match your lifestyle and reflect your style, with a focus on clean, functional, and beautiful spaces."
      },
      {
        "question": "Where do you provide bathroom renovation services?",
        "answer": "The company serves homeowners in Kitchener, Waterloo, Cambridge, and Guelph."
      }
    ],
    "pageEyebrow": "FULL-SERVICE DESIGN-BUILD RENOVATIONS",
    "pageTitle": "Bathroom Renovation"
  },
  {
    "name": "Home Addition",
    "slug": "home-addition",
    "description": "Go Hard Corporation designs and builds home additions for homeowners who need more space and better functionality without leaving the home they love. The company specializes in additions as part of its full-service design-build offering, guiding clients through design, permits, and construction. Each addition is tailored to the home and the homeowner's lifestyle so the finished space feels intentional and fully integrated.",
    "shortDescription": "Increase your home's space with a custom-designed addition built through a full-service renovation process.",
    "features": [
      "Custom addition designs",
      "Added living space",
      "Increased functionality",
      "Value-adding renovations",
      "Design and permit coordination",
      "Full construction management"
    ],
    "faqs": [
      {
        "question": "Do you design custom home additions?",
        "answer": "Yes. Custom designs are listed as a feature of the home addition service, and the company tailors renovations to each homeowner's lifestyle and style."
      },
      {
        "question": "Can you manage a home addition from planning through construction?",
        "answer": "Yes. Go Hard Corporation handles projects from design and permits through the build as a full-service design-build renovation company."
      },
      {
        "question": "Will a home addition improve how our house functions?",
        "answer": "That is a core focus of the service. The company emphasizes increased functionality and creating spaces that work better for everyday life."
      },
      {
        "question": "Do home additions add value to a property?",
        "answer": "Value addition is listed as one of the service features, alongside increased space and functionality."
      },
      {
        "question": "Who will be involved in the addition project?",
        "answer": "Projects are supported by interior designers, project managers, and skilled builders working together through the design-build process."
      },
      {
        "question": "What areas do you serve for home additions?",
        "answer": "Go Hard Corporation serves Kitchener, Waterloo, Cambridge, and Guelph."
      }
    ],
    "pageEyebrow": "FULL-SERVICE DESIGN-BUILD RENOVATIONS",
    "pageTitle": "Home Addition"
  },
  {
    "name": "Outdoor Spaces",
    "slug": "outdoor-spaces",
    "description": "Go Hard Corporation creates customized outdoor spaces that extend the comfort and usability of your home beyond its interior. The service includes patios, decks, and landscaping designed to enhance outdoor living while reflecting the homeowner's style and practical needs. Like the company's interior renovation work, outdoor projects are shaped around functional design and quality execution.",
    "shortDescription": "Enhance your outdoor living with customized patios, decks, and landscaping solutions.",
    "features": [
      "Custom outdoor designs",
      "Patio construction",
      "Deck construction",
      "Landscaping integration",
      "Functional outdoor living improvements",
      "Style-aligned renovation planning"
    ],
    "faqs": [
      {
        "question": "What types of outdoor projects do you take on?",
        "answer": "Go Hard Corporation lists patios, decks, and landscaping as part of its outdoor spaces service."
      },
      {
        "question": "Can you customize the design of an outdoor space?",
        "answer": "Yes. The company describes this service as customized and focused on designs that match the homeowner's needs and style."
      },
      {
        "question": "Do you focus on function as well as appearance outdoors?",
        "answer": "Yes. Go Hard Corporation emphasizes creating spaces that are both functional and beautiful across its renovation services."
      },
      {
        "question": "Will the outdoor design feel connected to the rest of the home?",
        "answer": "The company states that each renovation is designed to reflect the homeowner's style and make the home feel personal and complete, which supports a cohesive result."
      },
      {
        "question": "Do you only handle major interior renovations?",
        "answer": "No. In addition to kitchens, bathrooms, and home additions, the company also offers customized outdoor spaces."
      },
      {
        "question": "Where do you build outdoor spaces?",
        "answer": "The company serves homeowners in Kitchener, Waterloo, Cambridge, and Guelph."
      }
    ],
    "pageEyebrow": "CUSTOM OUTDOOR LIVING",
    "pageTitle": "Outdoor Spaces"
  }
] as const;

export const TESTIMONIALS = [
  {
    "author": "Paul Schrumm",
    "text": "Thank you Wyatt and Coleman, it was our pleasure to welcome both of these young men into our home. In addition to being skilled workmen, they were always respectful for our home, time and expectations.",
    "rating": 5,
    "source": "Google"
  },
  {
    "author": "Mike Murray",
    "text": "We are extremely pleased with the work performed by Go Hard Corporation.",
    "rating": 5,
    "source": "Google"
  },
  {
    "author": "Nathan Watson",
    "text": "Once again Go Hard didn't disappoint! After a great experience with them on our kitchen reno...",
    "rating": 5,
    "source": "Google"
  },
  {
    "author": "Pradeep Kr",
    "text": "It was wonderful experience taking service from Pinnacle improvements co. Needed to fix drywall and paint issues...",
    "rating": 5,
    "source": "Google"
  },
  {
    "author": "Alex Mercer",
    "text": "Quality of the work was impeccable. Our main wall in the living room needed a makeover/renovation.",
    "rating": 10,
    "source": "Google"
  },
  {
    "author": "Kelly Mercer",
    "text": "Go Hard has just completed an Accent Wall in our new home and we couldn’t be happier...",
    "rating": 5,
    "source": "Google"
  },
  {
    "author": "Kathy Lalonde",
    "text": "This company really is incredible. I don't know if some of you have had workers come out to your home...",
    "rating": 5,
    "source": "Google"
  }
] as const;

export const PROJECTS = [
  {
    "title": "Master Ensuite Renovation",
    "description": "Paul Schrumm praised the team's skilled workmanship and respectful approach while working inside the home.",
    "category": "Bathroom Renovation"
  },
  {
    "title": "Living Room and Kitchen Renovation",
    "description": "Mike Murray said he was extremely pleased with the work performed by Go Hard Corporation.",
    "category": "Kitchen Renovation"
  },
  {
    "title": "Fireplace Feature Wall",
    "description": "Nathan Watson described another positive experience with the company following an earlier kitchen renovation.",
    "category": "Living Space Renovation"
  },
  {
    "title": "Drywall and Paint Repair",
    "description": "Pradeep Kr referenced drywall and paint issue repairs as part of the work completed.",
    "category": "Interior Repair"
  },
  {
    "title": "Living Room Renovation",
    "description": "Alex Mercer highlighted impeccable quality on a living room wall makeover and renovation.",
    "category": "Living Space Renovation"
  },
  {
    "title": "Accent Wall Renovation",
    "description": "Kelly Mercer said the company completed an accent wall in a new home and that the result left them very happy.",
    "category": "Living Space Renovation"
  },
  {
    "title": "Various Renovation Projects",
    "description": "Kathy Lalonde described the company as incredible based on renovation work completed in the home.",
    "category": "General Renovation"
  }
] as const;

export const TEAM_MEMBERS = [
  {
    "name": "Chris Smith",
    "role": "Owner/Partner",
    "bio": null
  }
] as const;

export const PRINCIPALS = [
  {
    "name": "Chris Smith",
    "role": "Owner/Partner",
    "bio": null
  }
] as const;

export const SERVICE_AREAS = [
  "Kitchener",
  "Waterloo",
  "Cambridge",
  "Guelph"
] as const;

export const PROCESS_STEPS = [
  {
    "title": "Consultation",
    "description": "Discuss your renovation needs and ideas."
  },
  {
    "title": "Design Phase",
    "description": "Our team creates tailored designs."
  },
  {
    "title": "Construction",
    "description": "Our skilled team brings your project to life."
  },
  {
    "title": "Final Walkthrough",
    "description": "Ensure everything meets your expectations."
  }
] as const;

export const TRUST_METRICS = {
  "yearsInBusiness": null,
  "projectsCompleted": null,
  "googleRating": null,
  "googleReviewCount": null,
  "certifications": [],
  "awards": []
} as const;

export const FAQ_ITEMS = [
  {
    "question": "What types of renovations does Go Hard Corporation specialize in?",
    "answer": "Go Hard Corporation specializes in kitchens, bathrooms, and home additions, and also offers customized outdoor spaces such as patios, decks, and landscaping."
  },
  {
    "question": "Do you provide design-build renovation services?",
    "answer": "Yes. The company is a full-service design-build renovation contractor that manages projects from design and permits through construction."
  },
  {
    "question": "Who will be involved in my renovation project?",
    "answer": "Projects are supported by interior designers, project managers, and skilled builders."
  },
  {
    "question": "What areas do you serve?",
    "answer": "Go Hard Corporation serves homeowners in Kitchener, Waterloo, Cambridge, and Guelph."
  },
  {
    "question": "What is your goal for each renovation?",
    "answer": "The company's goal is to help homeowners enjoy clean, functional, and beautiful spaces that match their lifestyle, reflect their style, and make the home feel personal and complete."
  },
  {
    "question": "What does your renovation process look like?",
    "answer": "The process includes consultation, design, construction, and a final walkthrough to make sure everything meets expectations."
  }
] as const;

export const CONTACT = {
  "phone": "519-212-1296",
  "email": "chris@gohardcorp.com",
  "address": "22 Glenbrook Crescent",
  "hours": null,
  "socialLinks": []
} as const;
