/**
 * Go Hard Corporation — site content data.
 * Auto-generated by Content Architect. Do not edit manually.
 * Re-generated on each pipeline build.
 */

export const SITE_ID = "go-hard-corporation";

export const PUBLIC_CONTENT = {
  "heroEyebrow": "Renovation contractor in Kitchener, Waterloo, Cambridge, and Guelph",
  "heroHeadline": "Full Home Renovations in Kitchener, Waterloo, Cambridge and Guelph",
  "heroSubheadline": "Create a home you love with our interior designers.",
  "heroPrimaryCta": {
    "label": "Get Your Free Design Estimate",
    "href": "/visualizer"
  },
  "heroSecondaryCta": {
    "label": "See Your Space Before You Build",
    "href": "/visualizer?mode=chat"
  },
  "businessHistory": null
} as const;

export const SERVICES = [
  {
    "name": "Kitchen Renovation",
    "slug": "kitchen-renovation",
    "description": "Transform your kitchen with quality renovations.",
    "shortDescription": "Transform your kitchen with quality renovations.",
    "features": [
      "Intentional design",
      "Functional space",
      "High quality materials"
    ],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Bathroom Renovation",
    "slug": "bathroom-renovation",
    "description": "Upgrade your bathroom with stylish features.",
    "shortDescription": "Upgrade your bathroom with stylish features.",
    "features": [
      "Modern designs",
      "Quality installations"
    ],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Home Additions",
    "slug": "home-additions",
    "description": "Expand your home to fit your needs.",
    "shortDescription": "Expand your home to fit your needs.",
    "features": [
      "Custom designs",
      "Professional craftsmanship"
    ],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Design and Build",
    "slug": "design-and-build",
    "description": "",
    "shortDescription": "",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Basement Renovations",
    "slug": "basement-renovations",
    "description": "",
    "shortDescription": "",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Decks, Fences & Outdoor Living",
    "slug": "decks-fences-outdoor-living",
    "description": "",
    "shortDescription": "",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  },
  {
    "name": "Interior Design",
    "slug": "interior-design",
    "description": "",
    "shortDescription": "",
    "features": [],
    "faqs": [],
    "pageEyebrow": null,
    "pageTitle": null
  }
] as const;

export const TESTIMONIALS = [
  {
    "author": "Kia Gaines",
    "text": "If you want to remove negative reviews from your Google Business, contact me via my profile; my contact details are listed there.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Paul Schrumm",
    "text": "Thank you Wyatt and Coleman, it was our pleasure to welcome both of these young men into our home. In addition to being skilled workmen, they were always respectful for our home, time and expectations. They cleaned up all work areas at the end of each day. Wyatt and Coleman completed several jobs for us, most importantly updating our master ensuite. Creating a “wet room” with glass wall and rain shower with a zero lip entrance, that will allow these seniors to “age in place” safely. In addition they added a kitchen backsplash, repaired a ceiling, upgraded living room flooring. Project manager and designer Liliana, was very patient with us offering many helpful suggestions to make our vision come true. We are both very happy to give a 5 star rating to all the Go Hard employees. Thank you.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Mike Murray",
    "text": "We are extremely pleased with the work performed by Go Hard Corporation. Our bungalow condo was starting to show its age, so we decided to have the main floor living room and kitchen repainted. That included all of the kitchen and island cupboards. In addition we had new quartz counter tops installed along with a new kitchen sink. We were very impressed with all of their employees. Liliana was terrific both as the project coordinator and her assistance with interior design. Their other employees always arrived on time and performed high quality work. They always cleaned up at the end of every workday. The work was completed by their employees Shane, Brent, Wyatt and Coleman. Top marks to all of them. We will certainily use them again. We highly recommend Go Hard Corporation for your renovation projects.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Nathan Watson",
    "text": "Once again Go Hard didn't disappoint! After a great experience with them on our kitchen reno, we had them do a fireplace feature wall in the familyroom. Wyatt and Coleman do excellent work. We love our new fireplace/ TV wall and can't wait to decorate the room! I highly recommend for your renovation.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Pradeep Kr",
    "text": "It was wonderful experience taking service from Pinnacle improvements co. Needed to fix drywall and paint issues. It was done preety quick and in timely manner. Ali was amazing with his work and the work done by him showed his professional expertise.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Alex Mercer",
    "text": "Quality of the work was impeccable. Our main wall in the living room needed a makeover/renovation. We Couldn’t have asked for anything better. They were friendly, professional and even helped reconnect our TV and hid all the cords. They truly went above and beyond our expectations. They were punctual, efficient and completed it all in 2 days. Any issues that came up, they found a way to make it work. If you are looking for a big or small renovation, I Couldn’t recommend them enough. 10/10",
    "rating": 10,
    "source": null
  },
  {
    "author": "Kelly Mercer",
    "text": "Go Hard has just completed an Accent Wall in our new home and we couldn’t be happier. Amazing craftsmanship, friendly, thorough, professional and their attention to detail was very impressive. We wouldn’t hesitate to use them again in the future.",
    "rating": 5,
    "source": null
  },
  {
    "author": "Stephanie Wagner",
    "text": "We recently renovated our entire main floor plus ensuite while living in the house, and I can’t say enough great things about this team. Go Hard came recommended by family, and I’m so glad we went with them. What could have been a stressful process felt smooth and manageable. Every day the space was left spotless, which made a huge difference with two adults working from home (and two dogs!) in the mix. The crew worked hard, respected our routines, and always took the time to answer my questions. A special thank you to Liliana - her advice and guidance on design selections were absolutely invaluable. I can’t imagine having made those choices without her thoughtful input. She truly elevated the whole experience. The quality of the work is exceptional, the project stayed on track, and the team was transparent and easy to trust throughout. I’m already thinking about what project I’ll be calling them for next.",
    "rating": 5,
    "source": null
  }
] as const;

export const PROJECTS = [
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  },
  {
    "title": "Project",
    "description": "",
    "category": null
  }
] as const;

export const TEAM_MEMBERS = [] as const;

export const PRINCIPALS = [] as const;

export const SERVICE_AREAS = [
  "Kitchener",
  "Waterloo",
  "Cambridge",
  "and Guelph"
] as const;

export const PROCESS_STEPS = [] as const;

export const TRUST_METRICS = {
  "yearsInBusiness": null,
  "projectsCompleted": null,
  "googleRating": null,
  "googleReviewCount": null,
  "certifications": [],
  "awards": []
} as const;

export const FAQ_ITEMS = [] as const;

export const CONTACT = {
  "phone": "519-212-1296",
  "email": "chris@gohardcorp.com",
  "address": "22 Glenbrook Crescent",
  "hours": "Mon-Fri 8am-5pm",
  "socialLinks": []
} as const;
