/**
 * Westmount Craftsmen — site content data.
 * Auto-generated by Content Architect. Do not edit manually.
 * Re-generated on each pipeline build.
 */

export const SITE_ID = "westmount-craftsmen";

export const PUBLIC_CONTENT = {
  "heroEyebrow": "FAMILY-OWNED & FULLY INSURED",
  "heroHeadline": "Love Your Home",
  "heroSubheadline": "Renovations Made Easy",
  "heroPrimaryCta": {
    "label": "Love Your Home",
    "href": "/visualizer"
  },
  "heroSecondaryCta": {
    "label": "Renovations Made Easy",
    "href": "/visualizer?mode=chat"
  },
  "businessHistory": "Westmount Craftsmen is a family-owned and fully insured general contractor serving the Kitchener Waterloo area. The company emphasizes a substantial front-end design phase so each renovation addresses the homeowner's problems, meets practical needs, and brings aesthetic goals to life. Its team is dedicated to delivering a finished product that exceeds expectations."
} as const;

export const SERVICES = [
  {
    "name": "Kitchen Renovation",
    "slug": "kitchen-renovation",
    "description": "Westmount Craftsmen creates kitchens that look and feel more spacious, and can plan additions when more room is needed. The goal is a kitchen that truly functions as the heart of the home while fitting your routine, needs, and aesthetic preferences. Their front-end design approach gives the team time to solve layout problems before construction begins.",
    "shortDescription": "Kitchen renovations designed to improve space, function, and the everyday experience of the heart of your home.",
    "features": [
      "Front-end kitchen design planning",
      "Layouts designed to look and feel more spacious",
      "Kitchen additions when extra space is needed",
      "Designs tailored to household routines",
      "Aesthetic planning aligned with homeowner goals"
    ],
    "faqs": [
      {
        "question": "Can you make my current kitchen feel bigger without adding onto the house?",
        "answer": "Yes. Westmount Craftsmen designs kitchens to look and feel more spacious by rethinking layout and flow. If more square footage is still needed, they can also plan an addition."
      },
      {
        "question": "Do you help with the kitchen design before construction starts?",
        "answer": "Yes. The company spends substantial time with homeowners at the front end of the design phase so the renovation solves real problems and reflects practical needs and aesthetic goals."
      },
      {
        "question": "Can the new kitchen be designed around how my family actually uses the space?",
        "answer": "Yes. Westmount Craftsmen focuses on designs that work with the household's daily routine, not just the appearance of the room."
      },
      {
        "question": "Do you only renovate existing kitchens, or can you expand them too?",
        "answer": "They can do both. Westmount Craftsmen renovates existing kitchens and can also add on to create the extra space needed for a better kitchen layout."
      },
      {
        "question": "What kind of renovation experience do you aim to provide?",
        "answer": "The company highlights a stress-free renovation process, high customer service, and an honest, straightforward approach to budget and pricing concerns."
      }
    ],
    "pageEyebrow": null,
    "pageTitle": "Kitchen Renovation"
  },
  {
    "name": "Bathroom Renovation",
    "slug": "bathroom-renovation",
    "description": "Westmount Craftsmen plans bathrooms with equal attention to aesthetics, layout, and long-term durability. Each renovation is designed to look fantastic, stay 100% watertight, and remain easy to maintain over time. The result is a bathroom built to last and tailored to how you live.",
    "shortDescription": "Bathroom renovations focused on beauty, layout, watertight construction, and easy long-term maintenance.",
    "features": [
      "Design planning that balances aesthetics and layout",
      "100% watertight bathroom construction",
      "Easy-to-maintain bathroom finishes and details",
      "Build quality intended to last",
      "Bathroom layouts tailored to daily use"
    ],
    "faqs": [
      {
        "question": "How do you make sure a renovated bathroom is built to last?",
        "answer": "Westmount Craftsmen plans bathrooms with aesthetics, layout, watertight construction, and ease of maintenance in mind so the finished space is built to last."
      },
      {
        "question": "Will the bathroom design be customized to my taste and lifestyle?",
        "answer": "Yes. Their design approach is tailored to the homeowner's tastes and lifestyle, with upfront planning focused on the problems the renovation needs to solve."
      },
      {
        "question": "Can you improve an awkward or inefficient bathroom layout?",
        "answer": "Yes. Layout is a core part of their bathroom renovation approach, helping the new room function better day to day while still looking fantastic."
      },
      {
        "question": "Are easy-to-clean finishes part of the plan?",
        "answer": "Yes. Westmount Craftsmen specifically notes that renovated bathrooms should be easy to maintain as well as attractive."
      },
      {
        "question": "Do you prioritize quality materials and finishes?",
        "answer": "Yes. The company highlights the use of high-quality products and finishes as part of its renovation approach."
      }
    ],
    "pageEyebrow": null,
    "pageTitle": "Bathroom Renovation"
  },
  {
    "name": "Basement Renovation",
    "slug": "basement-renovation",
    "description": "Westmount Craftsmen transforms unfinished or underused basements into bright, spacious showpieces. The space can be designed for family use, such as a game room, or configured as a legal rental unit depending on the homeowner's goals. Their basement renovations are positioned as a way to add function and increase property value.",
    "shortDescription": "Basement renovations that turn underused space into bright living areas, game rooms, or legal rental units.",
    "features": [
      "Bright, spacious basement transformations",
      "Family game room renovation planning",
      "Legal rental unit focused basement layouts",
      "Design aimed at increasing property value",
      "Front-end design based on homeowner goals"
    ],
    "faqs": [
      {
        "question": "Can you turn my basement into living space my family will actually use?",
        "answer": "Yes. Westmount Craftsmen renovates basements into bright, spacious areas suited to family use, including game rooms and other finished living spaces."
      },
      {
        "question": "Do you work on basement suites or rental-oriented layouts?",
        "answer": "Yes. Their basement renovation offering specifically includes legal rental unit style transformations when that fits the homeowner's goals."
      },
      {
        "question": "Will a basement renovation help my home's value?",
        "answer": "The company describes basement renovations as a way to increase property value while making the space more functional."
      },
      {
        "question": "How do you keep a basement from feeling dark or cramped?",
        "answer": "Their focus is on transforming the basement into a bright and spacious showpiece rather than leaving it feeling closed in."
      },
      {
        "question": "Is the design phase important for basement work?",
        "answer": "Yes. Westmount Craftsmen uses a front-end design approach to make sure the finished basement addresses the homeowner's needs before construction starts."
      }
    ],
    "pageEyebrow": null,
    "pageTitle": "Basement Renovation"
  },
  {
    "name": "Home Renovation",
    "slug": "home-renovation",
    "description": "Westmount Craftsmen approaches home renovations by first evaluating what works and what does not in the current design. From there, the layout is reworked so the home flows better with your tastes and your household's daily routine. Their design-heavy process is meant to solve practical problems while improving the way the home feels and functions.",
    "shortDescription": "Home renovations that rework layout and flow to better match your tastes, routine, and the way your household lives.",
    "features": [
      "Whole-home evaluation of what works and what does not",
      "Redesigned layouts that improve flow",
      "Renovations aligned with household routines",
      "Tailored design approach based on tastes and lifestyle",
      "General contracting for broader home transformation"
    ],
    "faqs": [
      {
        "question": "How do you approach a whole-home renovation?",
        "answer": "Westmount Craftsmen first evaluates what works and what does not in the current design, then pieces the home back together in a way that better supports the household's routines and style."
      },
      {
        "question": "Can you help improve flow between rooms?",
        "answer": "Yes. The company focuses on creating a design that flows with your tastes and the way your household moves through the home each day."
      },
      {
        "question": "Is the renovation customized or based on standard layouts?",
        "answer": "Their design approach is tailored to your tastes, lifestyle, and practical needs rather than a one-size-fits-all plan."
      },
      {
        "question": "Do you work on bigger design changes or just cosmetic updates?",
        "answer": "Westmount Craftsmen offers home renovations that can involve reworking the overall design of the space, not just surface-level changes."
      },
      {
        "question": "How do you handle design concerns and budget questions?",
        "answer": "They emphasize substantial upfront design work plus an honest and straightforward approach to budget and pricing concerns."
      }
    ],
    "pageEyebrow": null,
    "pageTitle": "Home Renovation"
  }
] as const;

export const TESTIMONIALS = [
  {
    "author": "Sandy E.",
    "text": "Westmount recently renovated our entire main floor including kitchen, bathroom, bedrooms, etc. From start to finish, the entire team were professional, pleasant and easy to communicate with. Nathan and Ed were extremely helpful whenever we reached out with any questions and/or concerns. Our Reno far exceeded our expectations and we couldn’t be more thrilled with the results. Absolutely love our “new home”! Definitely recommend!",
    "rating": 5,
    "source": null
  }
] as const;

export const PROJECTS = [
  {
    "title": "Kiwanis Main Floor Renovation in Kitchener",
    "description": "Main floor renovation project in Kitchener.",
    "category": "Main Floor Renovation"
  },
  {
    "title": "Hostetler Basement Renovation in New Hamburg",
    "description": "Basement renovation project in New Hamburg.",
    "category": "Basement Renovation"
  },
  {
    "title": "Parkhaven Kitchen Renovation in St Jacobs",
    "description": "Kitchen renovation project in St Jacobs.",
    "category": "Kitchen Renovation"
  },
  {
    "title": "Parkhaven Ensuite Bathroom Renovation in St Jacobs",
    "description": "Ensuite bathroom renovation project in St Jacobs.",
    "category": "Ensuite Bathroom Renovation"
  },
  {
    "title": "Merganser Home Renovation in Guelph",
    "description": "Home renovation project in Guelph.",
    "category": "Home Renovation"
  },
  {
    "title": "Moorlands Basement Renovation in Kitchener",
    "description": "Basement renovation project in Kitchener.",
    "category": "Basement Renovation"
  },
  {
    "title": "Winchester Kitchen Renovation in Waterloo",
    "description": "Kitchen renovation project in Waterloo.",
    "category": "Kitchen Renovation"
  },
  {
    "title": "Pioneer Ridge Bathroom Renovations in Kitchener",
    "description": "Bathroom renovation project in Kitchener.",
    "category": "Bathroom Renovation"
  },
  {
    "title": "New Hampshire Home Renovation in Waterloo",
    "description": "Home renovation project in Waterloo.",
    "category": "Home Renovation"
  },
  {
    "title": "Valebrook Basement Suite in Kitchener",
    "description": "Basement suite project in Kitchener.",
    "category": "Basement Suite"
  },
  {
    "title": "Greenwood Kitchen Renovation in Cambridge",
    "description": "Kitchen renovation project in Cambridge.",
    "category": "Kitchen Renovation"
  },
  {
    "title": "Spring Tide Ensuite Bathroom Renovation in Waterloo",
    "description": "Ensuite bathroom renovation project in Waterloo.",
    "category": "Ensuite Bathroom Renovation"
  }
] as const;

export const TEAM_MEMBERS = [] as const;

export const PRINCIPALS = [] as const;

export const SERVICE_AREAS = [
  "Kitchener",
  "Waterloo",
  "Cambridge",
  "New Hamburg",
  "St Jacobs",
  "Guelph"
] as const;

export const PROCESS_STEPS = [
  {
    "title": "Front-End Design Phase",
    "description": "Westmount Craftsmen spends a substantial amount of time working with homeowners at the front end of the design phase."
  },
  {
    "title": "Design Around Your Needs",
    "description": "Each aspect of the design is developed to address your problems, meet your needs, and make your aesthetic dreams a reality."
  },
  {
    "title": "Finished Product That Exceeds Expectations",
    "description": "The entire team is dedicated to delivering a finished product that exceeds expectations."
  }
] as const;

export const TRUST_METRICS = {
  "yearsInBusiness": null,
  "projectsCompleted": null,
  "googleRating": null,
  "googleReviewCount": null,
  "certifications": [],
  "awards": []
} as const;

export const FAQ_ITEMS = [
  {
    "question": "What areas do you serve?",
    "answer": "Westmount Craftsmen serves Kitchener, Waterloo, Cambridge, and nearby cities, with portfolio examples in New Hamburg, St Jacobs, and Guelph."
  },
  {
    "question": "What types of renovations do you offer?",
    "answer": "The company offers kitchen renovations, bathroom renovations, basement renovations, and broader home renovations, with project examples that also include main floor renovations and basement suites."
  },
  {
    "question": "What makes Westmount Craftsmen different?",
    "answer": "Westmount Craftsmen describes itself as a family-owned and fully insured contractor with a unique design approach, a substantial front-end design phase, and a team dedicated to a finished product that exceeds expectations."
  },
  {
    "question": "How do you approach design?",
    "answer": "They spend substantial time working with homeowners early in the design phase so each part of the renovation addresses real problems, meets practical needs, and supports the homeowner's aesthetic goals."
  },
  {
    "question": "How do you handle pricing and customer service?",
    "answer": "The company highlights a stress-free renovation experience, the highest level of customer service available, and an honest and straightforward approach to budget and pricing concerns."
  }
] as const;

export const CONTACT = {
  "phone": "(519) 635-7089",
  "email": null,
  "address": "100 Campbell Ave #11",
  "hours": null,
  "socialLinks": []
} as const;
