import { registerSection } from '@/lib/section-registry';
import type { SectionId } from '@/lib/section-types';
import type { SectionComponent } from '@/lib/section-registry';
import { WarmLeadHero } from '../_shared-warm-lead/hero';
import { WarmLeadServices } from '../_shared-warm-lead/services';
import { WarmLeadAbout } from '../_shared-warm-lead/about';
import { WarmLeadWhyUs } from '../_shared-warm-lead/why-us';
import { WarmLeadTestimonials } from '../_shared-warm-lead/testimonials';
import { WarmLeadPortfolio } from '../_shared-warm-lead/portfolio';
import { WarmLeadProcess } from '../_shared-warm-lead/process';
import { WarmLeadContactCta } from '../_shared-warm-lead/contact-cta';
import { WarmLeadFooter } from '../_shared-warm-lead/footer-section';
registerSection('custom:gilbert-burke-hero' as SectionId, WarmLeadHero as SectionComponent);
registerSection('custom:gilbert-burke-services' as SectionId, WarmLeadServices as SectionComponent);
registerSection('custom:gilbert-burke-about' as SectionId, WarmLeadAbout as SectionComponent);
registerSection('custom:gilbert-burke-why-us' as SectionId, WarmLeadWhyUs as SectionComponent);
registerSection('custom:gilbert-burke-testimonials' as SectionId, WarmLeadTestimonials as SectionComponent);
registerSection('custom:gilbert-burke-gallery' as SectionId, WarmLeadPortfolio as SectionComponent);
registerSection('custom:gilbert-burke-process' as SectionId, WarmLeadProcess as SectionComponent);
registerSection('custom:gilbert-burke-footer' as SectionId, WarmLeadFooter as SectionComponent);
registerSection('custom:gilbert-burke-contact-cta' as SectionId, WarmLeadContactCta as SectionComponent);
