#!/usr/bin/env node
/**
 * Provision a new tenant from scraped data.
 * Usage: node provision.mjs --site-id example-reno --data /tmp/provisioned.json --domain example.norbotsystems.com --tier accelerate
 */

import { createClient } from '@supabase/supabase-js';
import { parseArgs } from 'node:util';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { inferServiceIcon, inferBadgeIcon, isStrongHero as _isStrongHero, filterTestimonials, filterPortfolio, filterServices } from './lib/quality-gates.mjs';

function loadEnv() {
  for (const envFile of ['.env.local', resolve(process.env.HOME, 'pipeline/scripts/.env')]) {
    try {
      const content = readFileSync(resolve(process.cwd(), envFile), 'utf-8');
      for (const line of content.split('\n')) {
        const match = line.match(/^([^#=]+)=(.*)$/);
        if (match) {
          const key = match[1].trim();
          if (!process.env[key]) process.env[key] = match[2].trim().replace(/^["']|["']$/g, '');
        }
      }
    } catch { /* ignore */ }
  }
}

loadEnv();

const requiredVars = ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'];
const missingVars = requiredVars.filter(v => !process.env[v] && !process.env[v === 'NEXT_PUBLIC_SUPABASE_URL' ? 'SUPABASE_URL' : 'SUPABASE_SERVICE_KEY']);
if (missingVars.length > 0) {
  console.error(`Missing required env vars: ${missingVars.join(', ')}`);
  console.error('Add to .env.local or ~/pipeline/scripts/.env');
  process.exit(1);
}

const { values: args } = parseArgs({
  options: {
    'site-id': { type: 'string' },
    data: { type: 'string' },
    domain: { type: 'string' },
    tier: { type: 'string', default: 'accelerate' },
    help: { type: 'boolean' },
  },
});

if (args.help || !args['site-id'] || !args.data || !args.domain) {
  console.log('Usage: node provision.mjs --site-id example-reno --data /tmp/provisioned.json --domain example.norbotsystems.com --tier accelerate');
  process.exit(args.help ? 0 : 1);
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const siteId = args['site-id'];
const domain = args.domain;
const tier = args.tier;
const data = JSON.parse(readFileSync(args.data, 'utf-8'));

console.log(`\nProvisioning tenant: ${siteId}`);
console.log(`Domain: ${domain}`);
console.log(`Tier: ${tier}`);
console.log('\u2500'.repeat(50));

// Sanitize "N/A"-like values to empty string — prevents literal "N/A" rendering on tenant sites
function sanitizeNA(val) {
  if (!val || typeof val !== 'string') return '';
  const lower = val.trim().toLowerCase();
  if (['n/a', 'na', 'not available', 'not specified', 'not applicable', 'unknown', 'none', '-', '—'].includes(lower)) return '';
  return val.trim();
}

// Quality gate: hero headline check (wraps shared function with local business_name)
function isStrongHero(headline) {
  return _isStrongHero(headline, data.business_name || '');
}

// Quality gates — filter out low-quality content
const testimonials = filterTestimonials(data.testimonials || []);
const validPortfolio = filterPortfolio(data.portfolio || []);
const validServices = filterServices(data.services || []);

// Build admin_settings rows
const businessInfo = {
  name: data.business_name || siteId,
  phone: data.phone || '',
  email: data.email || '',
  payment_email: data.email || '',
  quotes_email: data.email || '',
  website: data.website || domain,
  address: sanitizeNA(data.address),
  city: data.city || '',
  province: data.province || 'ON',
  postal: sanitizeNA(data.postal),
};

const branding = {
  tagline: data.tagline || data.hero_headline || '',
  colors: {
    primary_hex: data.primary_color_hex || '#1565C0',
    primary_oklch: data._meta?.primary_oklch || '0.45 0.18 250',
  },
  socials: Object.entries({
    social_facebook: 'Facebook', social_instagram: 'Instagram',
    social_houzz: 'Houzz', social_google: 'Google',
    social_twitter: 'X', social_linkedin: 'LinkedIn',
    social_youtube: 'YouTube', social_tiktok: 'TikTok',
    social_pinterest: 'Pinterest',
  }).filter(([key]) => data[key]).map(([key, label]) => ({ label, href: data[key] })),
  // Favicon: use logo URL if available (layout.tsx resizes client-side)
  faviconUrl: data.logo_url || '',
  // OG image for social sharing (generated by tenant-builder)
  ogImageUrl: data._og_image_url || '',
};

const companyProfile = {
  principals: Array.isArray(data.principals) ? data.principals.join(', ') : (data.principals || ''),
  founded: sanitizeNA(data.founded_year),
  booking: sanitizeNA(data.booking_url),
  serviceArea: data.service_area || `${data.city || ''}, ${data.province || 'ON'} and surrounding areas`,
  hours: sanitizeNA(data.business_hours),
  certifications: data.certifications || [],
  testimonials: testimonials.map(t => ({
    author: t.author,
    quote: t.quote,
    projectType: t.project_type || 'Renovation',
  })),
  aboutCopy: data.about_copy || [],
  mission: sanitizeNA(data.mission),
  services: validServices.map(s => ({
    name: s.name,
    slug: s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
    description: s.description || '',
    features: s.features || [],
    packages: (s.packages || []).map(p => ({
      name: p.name,
      startingPrice: p.starting_price,
      description: p.description,
    })),
    iconHint: inferServiceIcon(s.name),
    imageUrl: s.image_urls?.[0] || '',
  })),
  heroHeadline: isStrongHero(data.hero_headline) ? data.hero_headline : undefined,
  heroSubheadline: data.hero_subheadline || undefined,
  heroImageUrl: data.hero_image_url || '',
  aboutImageUrl: data.about_image_url || '',
  logoUrl: data.logo_url || '',
  trustBadges: (() => {
    // Verifiable badge keyword filter — reject fabricated badges
    const VERIFIABLE_BADGE_KEYWORDS = [
      'licensed', 'insured', 'bonded', 'wsib', 'bbb', 'accredit',
      'renomark', 'warranty', 'guarantee', 'tarion', 'member', 'association',
      'certified', 'registered', 'approved', 'code', 'safety',
    ];
    return (data.trust_badges || [])
      .filter(b => {
        const lower = (b.label || '').toLowerCase();
        return VERIFIABLE_BADGE_KEYWORDS.some(kw => lower.includes(kw));
      })
      .map(b => ({ label: b.label, iconHint: inferBadgeIcon(b.label) }));
  })(),
  whyChooseUs: data.why_choose_us || [],
  values: (data.values && data.values.length > 0) ? data.values.map(v => ({ ...v, iconHint: v.iconHint || 'heart' })) : [],
  processSteps: (data.process_steps && data.process_steps.length > 0) ? data.process_steps : [],
  teamMembers: (data.team_members || []).map(m => ({
    name: m.name,
    role: m.role || '',
    photoUrl: m.photo_url || '',
    bio: m.bio,
  })),
  portfolio: validPortfolio.map(p => ({
    title: p.title || '',
    description: p.description || '',
    imageUrl: p.image_url || '',
    serviceType: p.service_type || '',
    location: p.location || '',
  })),
  trustMetrics: data._trust_metrics || {},
};

// Upsert admin_settings rows
const rows = [
  { key: 'business_info', value: businessInfo, description: `${siteId} business info` },
  { key: 'branding', value: branding, description: `${siteId} branding` },
  { key: 'company_profile', value: companyProfile, description: `${siteId} company profile` },
  { key: 'plan', value: { tier }, description: `${siteId} plan tier` },
  { key: 'quote_assistance', value: tier === 'elevate' ? { mode: 'none' } : { mode: 'range', rangeBand: 10000 }, description: `${siteId} quote assistance config` },
];

// ─── Upsert with rollback on failure ────────────────────────────────────────
const completedKeys = [];
let provisionFailed = false;

for (const row of rows) {
  console.log(`  Upserting: ${row.key}`);
  const { error } = await supabase
    .from('admin_settings')
    .upsert({
      site_id: siteId,
      key: row.key,
      value: row.value,
      description: row.description,
    }, { onConflict: 'site_id,key' });

  if (error) {
    console.error(`  ✗ Error upserting ${row.key}: ${error.message}`);
    provisionFailed = true;
    break;
  }
  completedKeys.push(row.key);
}

// Upsert tenants table (only if admin_settings succeeded)
if (!provisionFailed) {
  console.log(`  Upserting tenant record`);
  const { error: tenantError } = await supabase
    .from('tenants')
    .upsert({
      site_id: siteId,
      domain: domain,
      plan_tier: tier,
      active: true,
    }, { onConflict: 'site_id' });

  if (tenantError) {
    console.error(`  ✗ Error upserting tenant: ${tenantError.message}`);
    provisionFailed = true;
  }
}

// ─── Rollback on failure ────────────────────────────────────────────────────
if (provisionFailed) {
  console.log('\n  ROLLING BACK — deleting partially provisioned rows...');
  for (const key of completedKeys) {
    const { error: delError } = await supabase
      .from('admin_settings')
      .delete()
      .eq('site_id', siteId)
      .eq('key', key);
    if (delError) console.error(`    Failed to rollback ${key}: ${delError.message}`);
    else console.log(`    ✓ Rolled back: ${key}`);
  }
  // Also clean up tenants table
  const { error: tDelError } = await supabase
    .from('tenants')
    .delete()
    .eq('site_id', siteId);
  if (!tDelError) console.log(`    ✓ Rolled back: tenants record`);
  console.log('  Rollback complete. Fix the issue and re-run.');
  process.exit(1);
}

// Update proxy.ts with new domain
console.log(`\n  Updating proxy.ts...`);
const proxyPath = resolve(process.cwd(), 'src/proxy.ts');
const proxyContent = readFileSync(proxyPath, 'utf-8');

if (proxyContent.includes(`'${domain}'`)) {
  console.log(`  Domain already in proxy.ts`);
} else {
  const lines = proxyContent.split('\n');
  let insertIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('DOMAIN_TO_SITE')) {
      // Find the closing };
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].includes('};')) {
          insertIndex = j;
          break;
        }
      }
      break;
    }
  }

  if (insertIndex > 0) {
    lines.splice(insertIndex, 0, `  '${domain}': '${siteId}',`);
    writeFileSync(proxyPath, lines.join('\n'));
    console.log(`  Added domain mapping: ${domain} \u2192 ${siteId}`);
  } else {
    console.log(`  WARNING: Could not find insertion point in proxy.ts. Add manually.`);
  }
}

console.log(`\nProvisioning complete!`);
console.log(`\nNext steps:`);
console.log(`  1. Add domain ${domain} to Vercel project`);
console.log(`  2. git add -A && git commit -m "feat: add tenant ${siteId}"`);
console.log(`  3. git push (triggers Vercel deploy)`);
console.log(`  4. Run: node scripts/onboarding/verify.mjs --url https://${domain} --site-id ${siteId}`);
