// @ts-nocheck — Auto-generated by Codex. Type issues are expected on Record index signatures.
'use client';

import type { ReactNode } from 'react';
import type { SectionBaseProps } from '@/lib/section-types';
import Image from 'next/image';
import Link from 'next/link';
import {
  StaggerContainer,
  StaggerItem,
  FadeInUp,
  FadeIn,
  ScaleIn,
  SlideInFromSide,
} from '@/components/motion';
import {
  SERVICES,
  TESTIMONIALS,
  PROJECTS,
  PUBLIC_CONTENT,
  TRUST_METRICS,
} from '@/lib/sites/go-hard-corporation';

// ── Shared Design System ──────────────────────────────────────

function SectionEyebrow({ children }: { children: ReactNode }) {
  return (
    <p className="text-xs font-semibold uppercase tracking-[0.28em] text-primary">
      {children}
    </p>
  );
}

const CARD =
  'rounded-[28px] bg-white shadow-[0_18px_44px_rgba(15,23,42,0.06)] hover:-translate-y-1 hover:shadow-[0_24px_56px_rgba(15,23,42,0.10)] transition-all duration-300';

const SECTION =
  'relative overflow-hidden py-16 md:py-20 lg:py-24';

const OLIVE = '#6B6854';
const CHARCOAL = '#222222';

function str(value: unknown): string {
  return typeof value === 'string' && value.trim() ? value.trim() : '';
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function cfg(obj: any, key: string): string {
  return str(obj?.[key]);
}

function num(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function list<T>(value: unknown): T[] {
  return Array.isArray(value) ? (value as T[]) : [];
}

function phoneHref(value: string): string {
  const cleaned = value.replace(/[^\d+]/g, '');
  return `tel:${cleaned || value}`;
}

function initials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('');
}

function stars(rating: number): string {
  return '★★★★★'.slice(0, Math.max(0, Math.min(5, rating)));
}

function contentValue(key: string, fallback = ''): string {
  const content = PUBLIC_CONTENT as Record<string, unknown>;
  return str(content[key]) || fallback;
}

function contentArray<T>(key: string): T[] {
  const content = PUBLIC_CONTENT as Record<string, unknown>;
  return list<T>(content[key]);
}

function metricValue(key: string): number | null {
  const metrics = TRUST_METRICS as Record<string, unknown>;
  return num(metrics[key]);
}

function imageFromItem(item: Record<string, unknown>): string {
  return (
    str(item['imageUrl']) ||
    str(item['image_url']) ||
    str(item['coverImage']) ||
    str(item['cover_image']) ||
    str(item['photoUrl']) ||
    str(item['photo_url']) ||
    str(item['src'])
  );
}

function badgeText(value: string): string {
  return value.toUpperCase();
}

function ImageFallback({
  title,
  subtitle,
  dark = false,
}: {
  title: string;
  subtitle?: string;
  dark?: boolean;
}) {
  return (
    <div
      className={`absolute inset-0 flex h-full w-full flex-col justify-end ${
        dark
          ? 'bg-[linear-gradient(135deg,rgba(34,34,34,0.92),rgba(107,104,84,0.72))]'
          : 'bg-[linear-gradient(135deg,rgba(107,104,84,0.88),rgba(34,34,34,0.6))]'
      } p-6 text-white`}
    >
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.18),transparent_38%),linear-gradient(180deg,transparent_20%,rgba(0,0,0,0.48)_100%)]" />
      <div className="relative">
        <p className="font-heading text-xl font-bold">{title}</p>
        {subtitle ? <p className="mt-2 max-w-sm text-sm text-white/80">{subtitle}</p> : null}
      </div>
    </div>
  );
}

function PrimaryButton({ children }: { children: ReactNode }) {
  return (
    <span className="inline-flex items-center justify-center rounded-full bg-primary px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-white transition duration-300 hover:scale-[1.02] hover:bg-[#5d5a49]">
      {children}
    </span>
  );
}

function SecondaryButton({ children }: { children: ReactNode }) {
  return (
    <span className="inline-flex items-center justify-center rounded-full border border-white/50 bg-white/10 px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-white backdrop-blur-sm transition duration-300 hover:scale-[1.02] hover:border-white hover:bg-white/18">
      {children}
    </span>
  );
}

function LightButton({ children }: { children: ReactNode }) {
  return (
    <span className="inline-flex items-center justify-center rounded-full bg-primary px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-white transition duration-300 hover:scale-[1.02] hover:bg-[#5d5a49]">
      {children}
    </span>
  );
}

function GhostButton({ children }: { children: ReactNode }) {
  return (
    <span className="inline-flex items-center justify-center rounded-full border border-stone-300 bg-white px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-stone-800 transition duration-300 hover:scale-[1.02] hover:border-primary hover:text-primary">
      {children}
    </span>
  );
}

function splitProjects() {
  const projects = list<Record<string, unknown>>(PROJECTS);
  return {
    primary: projects.slice(0, 3),
    gallery: projects.slice(0, 4),
  };
}

// ── Section Components ──────────────────────────────────────

export function HeroSection({ branding, config, tokens, className }: SectionBaseProps) {
  const heroHeadline =
    contentValue('heroHeadline') ||
    cfg(config, 'heroHeadline') ||
    cfg(config, 'hero_headline') ||
    'Full Home Renovations in Kitchener, Waterloo, Cambridge and Guelph';
  const heroSubheadline =
    contentValue('heroSubheadline') ||
    cfg(config, 'heroSubheadline') ||
    cfg(config, 'hero_subheadline') ||
    'Creating beautiful bespoke and functional spaces.';
  const heroEyebrow =
    contentValue('heroEyebrow') ||
    cfg(config, 'heroEyebrow') ||
    cfg(config, 'hero_eyebrow') ||
    'Full Home Renovations';
  const heroImage =
    cfg(config, 'heroImageUrl') ||
    cfg(config, 'hero_image_url') ||
    imageFromItem(splitProjects().primary[0] ?? {});
  const locationLine = contentArray<string>('serviceAreas').join(' • ');
  const principal = contentArray<Record<string, unknown>>('principals')[0];
  const principalName = str(principal?.name) || 'Chris Smith';
  const phone = str(branding.phone);
  const email = str(branding.email);

  return (
    <section className={`${SECTION} bg-stone-950 text-white ${className ?? ''}`}>
      <div className="absolute inset-0">
        {heroImage ? (
          <Image
            src={heroImage}
            alt={branding.name || 'Go Hard Corporation renovation project'}
            fill
            priority
            className="object-cover"
          />
        ) : (
          <div className="absolute inset-0 bg-[linear-gradient(125deg,#2a2a28_0%,#6B6854_45%,#171717_100%)]" />
        )}
        <div className="absolute inset-0 bg-black/45" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.12),transparent_28%),radial-gradient(circle_at_bottom_right,rgba(107,104,84,0.32),transparent_32%)]" />
      </div>

      <div className="relative mx-auto grid min-h-[60vh] max-w-7xl items-end gap-8 px-6 pb-10 pt-28 sm:px-8 md:pb-14 lg:grid-cols-[minmax(0,1fr)_340px] lg:px-10 xl:px-14">
        <StaggerContainer className="max-w-3xl">
          <FadeInUp>
            <SectionEyebrow>{badgeText(heroEyebrow)}</SectionEyebrow>
          </FadeInUp>
          <FadeInUp>
            <h1 className="mt-5 max-w-4xl font-heading text-4xl font-bold leading-[0.96] text-white sm:text-5xl md:text-6xl lg:text-[5.25rem]">
              {heroHeadline}
            </h1>
          </FadeInUp>
          <FadeInUp>
            <p className="mt-6 max-w-2xl font-body text-base leading-7 text-white/82 sm:text-lg md:text-xl">
              {heroSubheadline}
            </p>
          </FadeInUp>
          <FadeInUp>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Link href="/visualizer">
                <PrimaryButton>See Your Space Before You Build</PrimaryButton>
              </Link>
              <Link href="/visualizer?mode=chat">
                <SecondaryButton>Get a Quick Estimate</SecondaryButton>
              </Link>
            </div>
          </FadeInUp>
          <FadeInUp>
            <div className="mt-10 grid max-w-2xl grid-cols-1 gap-3 text-sm text-white/76 sm:grid-cols-3 sm:gap-6">
              <div className="border-l border-white/30 pl-4">
                <p className="font-body uppercase tracking-[0.18em] text-white/55">Service Area</p>
                <p className="mt-2 font-body leading-6">{locationLine || 'Kitchener • Waterloo • Cambridge • Guelph'}</p>
              </div>
              <div className="border-l border-white/30 pl-4">
                <p className="font-body uppercase tracking-[0.18em] text-white/55">Design-Build Lead</p>
                <p className="mt-2 font-body leading-6">{principalName}</p>
              </div>
              <div className="border-l border-white/30 pl-4">
                <p className="font-body uppercase tracking-[0.18em] text-white/55">Reach Us</p>
                <p className="mt-2 font-body leading-6">
                  {phone || email || 'Consultations available now'}
                </p>
              </div>
            </div>
          </FadeInUp>
        </StaggerContainer>

        <FadeIn className="lg:justify-self-end">
          <div className="relative overflow-hidden rounded-[28px] border border-white/15 bg-white/10 p-6 backdrop-blur-md shadow-[0_18px_44px_rgba(0,0,0,0.18)]">
            <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,0.14),rgba(255,255,255,0.04))]" />
            <div className="relative">
              <SectionEyebrow>Book a Free Consultation</SectionEyebrow>
              <p className="mt-4 font-heading text-3xl font-bold leading-tight text-white">
                Smart planning up front. Clean execution all the way through.
              </p>
              <p className="mt-4 font-body text-sm leading-6 text-white/80">
                From permits and drawings to construction and finishing details, the same team
                stays responsible for your project from first meeting to final walkthrough.
              </p>
              <div className="mt-6 grid gap-3 text-sm text-white/80">
                <div className="rounded-2xl border border-white/10 bg-black/15 px-4 py-3">
                  Kitchens, baths, additions, and outdoor living spaces.
                </div>
                <div className="rounded-2xl border border-white/10 bg-black/15 px-4 py-3">
                  Interior design support and project management built in.
                </div>
              </div>
              <div className="mt-6 flex flex-col gap-3">
                <Link href="/visualizer">
                  <PrimaryButton>Start Your Renovation</PrimaryButton>
                </Link>
                <Link href="/visualizer?mode=chat" className="text-sm font-semibold uppercase tracking-[0.18em] text-white/82 transition hover:text-white">
                  Book a Consultation
                </Link>
              </div>
            </div>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

export function ServicesSection({ branding, config, tokens, className }: SectionBaseProps) {
  const services = list<Record<string, unknown>>(SERVICES);
  const gallery = splitProjects().gallery;

  return (
    <section className={`${SECTION} bg-white text-stone-900 ${className ?? ''}`}>
      <div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10 xl:px-14">
        <FadeInUp>
          <div className="mx-auto max-w-3xl text-center">
            <SectionEyebrow>Our Services</SectionEyebrow>
            <h2 className="mt-5 font-heading text-3xl font-bold leading-tight text-stone-900 sm:text-4xl md:text-5xl">
              Designed for real life. Built to hold up beautifully.
            </h2>
            <p className="mx-auto mt-5 max-w-2xl font-body text-base leading-7 text-stone-600 sm:text-lg">
              Go Hard Corporation manages the entire renovation arc, pairing detailed planning with
              disciplined site execution so each room feels intentional, durable, and personal.
            </p>
          </div>
        </FadeInUp>

        <StaggerContainer className="mt-12 grid gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)]">
          <div className="grid gap-6 md:grid-cols-2">
            {services.map((service, index) => {
              const name = str(service.name) || `Service ${index + 1}`;
              const description =
                str(service.shortDescription) ||
                str(service.description) ||
                'Thoughtful renovation planning and construction tailored to your home.';
              const features = list<string>(service.features).slice(0, 4);
              const imageUrl =
                imageFromItem(service) ||
                imageFromItem(gallery[index] ?? {}) ||
                imageFromItem(gallery[0] ?? {});

              return (
                <StaggerItem key={name} className="h-full">
                  <article className={`${CARD} group flex h-full flex-col overflow-hidden border border-stone-200/80`}>
                    <div className="relative h-56 overflow-hidden">
                      {imageUrl ? (
                        <Image
                          src={imageUrl}
                          alt={name}
                          fill
                          className="object-cover transition duration-500 group-hover:scale-105"
                        />
                      ) : (
                        <ImageFallback title={name} subtitle={description} />
                      )}
                      <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.34))]" />
                    </div>
                    <div className="flex flex-1 flex-col p-6">
                      <SectionEyebrow>{name}</SectionEyebrow>
                      <h3 className="mt-4 font-heading text-2xl font-bold text-stone-900">{name}</h3>
                      <p className="mt-3 font-body text-sm leading-6 text-stone-600">{description}</p>
                      <ul className="mt-5 grid gap-2">
                        {features.map((feature) => (
                          <li key={feature} className="flex items-start gap-3 font-body text-sm leading-6 text-stone-700">
                            <span className="mt-2 h-1.5 w-1.5 rounded-full bg-primary" />
                            <span>{feature}</span>
                          </li>
                        ))}
                      </ul>
                      <div className="mt-6">
                        <Link href="/visualizer">
                          <LightButton>See Your Space Before You Build</LightButton>
                        </Link>
                      </div>
                    </div>
                  </article>
                </StaggerItem>
              );
            })}
          </div>

          <StaggerItem>
            <aside className="rounded-[32px] bg-stone-50 p-4 sm:p-5 lg:sticky lg:top-10">
              <div className="rounded-[28px] bg-stone-950 px-6 py-8 text-white">
                <SectionEyebrow>Design-Build Focus</SectionEyebrow>
                <h3 className="mt-4 font-heading text-3xl font-bold leading-tight">
                  A single team handling concept, approvals, and construction.
                </h3>
                <p className="mt-4 font-body text-sm leading-6 text-white/78">
                  That continuity keeps communication sharp and protects the details that make a
                  renovation feel considered instead of improvised.
                </p>
              </div>
              <div className="mt-4 grid grid-cols-2 gap-3">
                {gallery.map((project, index) => {
                  const title =
                    str(project.title) ||
                    str(project.name) ||
                    ['Kitchen detail', 'Bathroom finish', 'Addition exterior', 'Outdoor retreat'][index] ||
                    `Project ${index + 1}`;
                  const imageUrl = imageFromItem(project);

                  return (
                    <ScaleIn key={`${title}-${index}`}>
                      <div className={`${CARD} group relative h-40 overflow-hidden border border-stone-200/70`}>
                        {imageUrl ? (
                          <Image
                            src={imageUrl}
                            alt={title}
                            fill
                            className="object-cover transition duration-500 group-hover:scale-105"
                          />
                        ) : (
                          <ImageFallback title={title} dark />
                        )}
                        <div className="absolute inset-0 bg-[linear-gradient(180deg,transparent_30%,rgba(0,0,0,0.58)_100%)]" />
                        <p className="absolute bottom-4 left-4 right-4 font-body text-sm font-semibold uppercase tracking-[0.18em] text-white">
                          {title}
                        </p>
                      </div>
                    </ScaleIn>
                  );
                })}
              </div>
              <div className="mt-5 rounded-[28px] border border-stone-200 bg-white p-6">
                <SectionEyebrow>AI Design Studio</SectionEyebrow>
                <p className="mt-4 font-heading text-2xl font-bold text-stone-900">
                  Upload a photo. Explore ideas. Move into planning with clarity.
                </p>
                <p className="mt-3 font-body text-sm leading-6 text-stone-600">
                  Use the visualizer to see layout directions, style cues, and rough scope before
                  the first site meeting.
                </p>
                <div className="mt-5 flex flex-col gap-3">
                  <Link href="/visualizer">
                    <LightButton>See Your Space Before You Build</LightButton>
                  </Link>
                  <Link href="/visualizer?mode=chat">
                    <GhostButton>Get a Quick Estimate</GhostButton>
                  </Link>
                </div>
              </div>
            </aside>
          </StaggerItem>
        </StaggerContainer>
      </div>
    </section>
  );
}

export function AboutSection({ branding, config, tokens, className }: SectionBaseProps) {
  const aboutCopy =
    contentValue('businessHistory') ||
    cfg(config, 'aboutCopy') ||
    cfg(config, 'about_copy') ||
    'Go Hard Corporation is a full-service design-build renovation company serving Kitchener, Waterloo, Cambridge, and Guelph.';
  const areas = contentArray<string>('serviceAreas');
  const people = contentArray<Record<string, unknown>>('principals');
  const lead = people[0];
  const leadName = str(lead?.name) || 'Chris Smith';
  const leadRole = str(lead?.role) || 'Owner / Partner';
  const leadBio =
    str(lead?.bio) ||
    'Trusted by homeowners for nearly a decade to create clean, functional, and beautiful spaces tailored to each lifestyle.';
  const imageUrl =
    cfg(config, 'aboutImageUrl') ||
    cfg(config, 'about_image_url') ||
    imageFromItem(splitProjects().primary[1] ?? {}) ||
    imageFromItem(splitProjects().primary[0] ?? {});

  return (
    <section className={`${SECTION} bg-stone-50 text-stone-900 ${className ?? ''}`}>
      <div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10 xl:px-14">
        <div className="grid items-center gap-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(360px,0.95fr)]">
          <SlideInFromSide direction="left" className="order-2 lg:order-1">
            <div className="max-w-2xl">
              <SectionEyebrow>About Us</SectionEyebrow>
              <h2 className="mt-5 font-heading text-3xl font-bold leading-tight text-stone-900 sm:text-4xl md:text-5xl">
                Renovation work that starts with listening and finishes with discipline.
              </h2>
              <p className="mt-6 font-body text-base leading-7 text-stone-600 sm:text-lg">
                {aboutCopy}
              </p>
              <div className="mt-8 grid gap-4 sm:grid-cols-2">
                <div className={`${CARD} border border-stone-200/80 p-6`}>
                  <SectionEyebrow>Who Leads It</SectionEyebrow>
                  <p className="mt-4 font-heading text-2xl font-bold text-stone-900">{leadName}</p>
                  <p className="mt-1 font-body text-sm uppercase tracking-[0.18em] text-primary">{leadRole}</p>
                  <p className="mt-4 font-body text-sm leading-6 text-stone-600">{leadBio}</p>
                </div>
                <div className={`${CARD} border border-stone-200/80 p-6`}>
                  <SectionEyebrow>Where They Work</SectionEyebrow>
                  <ul className="mt-4 grid gap-2">
                    {(areas.length ? areas : ['Kitchener', 'Waterloo', 'Cambridge', 'Guelph']).map((area) => (
                      <li key={area} className="flex items-center gap-3 font-body text-sm text-stone-700">
                        <span className="h-2.5 w-2.5 rounded-full bg-primary" />
                        <span>{area}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                <Link href="/visualizer">
                  <LightButton>See Your Space Before You Build</LightButton>
                </Link>
                {str(branding.phone) ? (
                  <a href={phoneHref(str(branding.phone))}>
                    <GhostButton>Talk to Our AI Receptionist</GhostButton>
                  </a>
                ) : (
                  <Link href="/visualizer?mode=chat">
                    <GhostButton>Get a Quick Estimate</GhostButton>
                  </Link>
                )}
              </div>
            </div>
          </SlideInFromSide>

          <SlideInFromSide direction="right" className="order-1 lg:order-2">
            <div className="relative">
              <div className="absolute -left-6 -top-6 hidden h-40 w-40 rounded-full bg-primary/10 blur-3xl lg:block" />
              <div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_160px] sm:grid-rows-[220px_180px]">
                <div className="group relative min-h-[420px] overflow-hidden rounded-[28px] sm:row-span-2">
                  {imageUrl ? (
                    <Image
                      src={imageUrl}
                      alt={branding.name || 'Go Hard Corporation team at work'}
                      fill
                      className="object-cover transition duration-500 group-hover:scale-105"
                    />
                  ) : (
                    <ImageFallback title={branding.name || 'Go Hard Corporation'} subtitle="Design-build renovations" />
                  )}
                  <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,0.06),rgba(0,0,0,0.52))]" />
                  <div className="absolute bottom-0 left-0 right-0 p-6 text-white">
                    <SectionEyebrow>Nearly a Decade of Trusted Builds</SectionEyebrow>
                    <p className="mt-3 max-w-md font-body text-sm leading-6 text-white/82">
                      Clean lines, practical planning, and craftsmanship that respects how your
                      home actually gets used every day.
                    </p>
                  </div>
                </div>
                <div className={`${CARD} border border-stone-200/80 p-5`}>
                  <SectionEyebrow>Approach</SectionEyebrow>
                  <p className="mt-4 font-heading text-xl font-bold text-stone-900">Functional first.</p>
                  <p className="mt-2 font-body text-sm leading-6 text-stone-600">
                    Every design move serves lifestyle, flow, and longevity.
                  </p>
                </div>
                <div className="rounded-[28px] bg-stone-950 p-5 text-white shadow-[0_18px_44px_rgba(15,23,42,0.12)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_24px_56px_rgba(15,23,42,0.18)]">
                  <SectionEyebrow>Promise</SectionEyebrow>
                  <p className="mt-4 font-heading text-xl font-bold">Thoughtful details, start to finish.</p>
                </div>
              </div>
            </div>
          </SlideInFromSide>
        </div>
      </div>
    </section>
  );
}

export function Footer({ branding, config, tokens, className }: SectionBaseProps) {
  const areas = contentArray<string>('serviceAreas');
  const navLinks = [
    { label: 'Services', href: '#services' },
    { label: 'About', href: '#about' },
    { label: 'Process', href: '#process' },
    { label: 'Testimonials', href: '#testimonials' },
  ];
  const socials = [
    { label: 'Instagram', href: 'https://www.instagram.com/' },
    { label: 'Facebook', href: 'https://www.facebook.com/' },
    { label: 'Houzz', href: 'https://www.houzz.com/' },
  ];

  return (
    <footer className={`relative overflow-hidden bg-stone-950 text-white ${className ?? ''}`}>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(107,104,84,0.28),transparent_30%),linear-gradient(180deg,rgba(255,255,255,0.02),transparent_24%)]" />
      <div className="relative mx-auto max-w-7xl px-6 py-14 sm:px-8 lg:px-10 xl:px-14">
        <FadeInUp>
          <div className="grid gap-8 rounded-[32px] border border-white/10 bg-white/5 px-6 py-8 backdrop-blur-sm lg:grid-cols-[minmax(0,1.2fr)_repeat(3,minmax(0,0.6fr))] lg:px-8">
            <div>
              <SectionEyebrow>Get in Touch</SectionEyebrow>
              <h2 className="mt-4 font-heading text-3xl font-bold leading-tight text-white sm:text-4xl">
                {branding.name || 'Go Hard Corporation'}
              </h2>
              <p className="mt-4 max-w-md font-body text-sm leading-6 text-white/72">
                Full-service design-build renovations for homeowners who want a beautiful result
                and a process that stays accountable from planning through construction.
              </p>
              <div className="mt-6 flex flex-col gap-3 sm:flex-row">
                <Link href="/visualizer">
                  <PrimaryButton>See Your Space Before You Build</PrimaryButton>
                </Link>
                <Link href="/visualizer?mode=chat">
                  <SecondaryButton>Get a Quick Estimate</SecondaryButton>
                </Link>
              </div>
            </div>

            <div>
              <SectionEyebrow>Contact</SectionEyebrow>
              <div className="mt-4 grid gap-3 font-body text-sm text-white/76">
                {str(branding.phone) ? <a href={phoneHref(str(branding.phone))}>{branding.phone}</a> : <span>Consultations available by request</span>}
                {str(branding.email) ? <a href={`mailto:${branding.email}`}>{branding.email}</a> : null}
                {str(branding.address) ? <p>{branding.address}</p> : null}
              </div>
            </div>

            <div>
              <SectionEyebrow>Navigate</SectionEyebrow>
              <ul className="mt-4 grid gap-3 font-body text-sm text-white/76">
                {navLinks.map((item) => (
                  <li key={item.label}>
                    <a href={item.href} className="transition hover:text-white">
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <SectionEyebrow>Service Area</SectionEyebrow>
              <div className="mt-4 flex flex-wrap gap-2">
                {(areas.length ? areas : ['Kitchener', 'Waterloo', 'Cambridge', 'Guelph']).map((area) => (
                  <span
                    key={area}
                    className="rounded-full border border-white/12 bg-white/6 px-3 py-2 font-body text-xs uppercase tracking-[0.16em] text-white/78"
                  >
                    {area}
                  </span>
                ))}
              </div>
              <div className="mt-6 flex flex-wrap gap-3">
                {socials.map((social) => (
                  <a
                    key={social.label}
                    href={social.href}
                    target="_blank"
                    rel="noreferrer"
                    className="rounded-full border border-white/12 px-4 py-2 font-body text-xs font-semibold uppercase tracking-[0.16em] text-white/78 transition hover:border-white hover:text-white"
                  >
                    {social.label}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </FadeInUp>

        <div className="mt-8 flex flex-col gap-3 border-t border-white/10 pt-6 font-body text-xs uppercase tracking-[0.18em] text-white/44 sm:flex-row sm:items-center sm:justify-between">
          <p>Built for Kitchener-Waterloo homeowners seeking bespoke renovation work.</p>
          <p>© {new Date().getFullYear()} {branding.name || 'Go Hard Corporation'}</p>
        </div>
      </div>
    </footer>
  );
}

export function Testimonials({ branding, config, tokens, className }: SectionBaseProps) {
  const testimonials = list<Record<string, unknown>>(TESTIMONIALS);

  return (
    <section className={`${SECTION} bg-white text-stone-900 ${className ?? ''}`}>
      <div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10 xl:px-14">
        <FadeInUp>
          <div className="mx-auto max-w-3xl text-center">
            <SectionEyebrow>Client Testimonials</SectionEyebrow>
            <h2 className="mt-5 font-heading text-3xl font-bold leading-tight text-stone-900 sm:text-4xl md:text-5xl">
              Clients remember the finish, but they notice the process first.
            </h2>
            <p className="mx-auto mt-5 max-w-2xl font-body text-base leading-7 text-stone-600 sm:text-lg">
              Respect for the home, reliable communication, and craftsmanship that feels calm and
              controlled are recurring themes across the feedback.
            </p>
          </div>
        </FadeInUp>

        <StaggerContainer className="mt-12 grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
          <StaggerItem>
            <div className="rounded-[32px] bg-stone-50 p-5 sm:p-6">
              <div className="rounded-[28px] bg-stone-950 p-8 text-white">
                <SectionEyebrow>What Homeowners Value</SectionEyebrow>
                <p className="mt-5 font-heading text-3xl font-bold leading-tight">
                  Skilled crews. Respectful presence. Work that feels considered.
                </p>
                <p className="mt-4 font-body text-sm leading-6 text-white/76">
                  Renovation quality is visible in the finished surfaces, but trust is built through
                  the day-to-day experience while the work is happening.
                </p>
                <div className="mt-8 grid gap-4 sm:grid-cols-3">
                  {[
                    'Clear site communication',
                    'Craftsmanship clients mention by name',
                    'A process grounded in expectations',
                  ].map((item) => (
                    <div key={item} className="rounded-2xl border border-white/10 bg-white/6 p-4 font-body text-sm leading-6 text-white/80">
                      {item}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </StaggerItem>

          <div className="grid gap-6 md:grid-cols-2">
            {testimonials.map((testimonial, index) => {
              const author = str(testimonial.author) || `Client ${index + 1}`;
              const text =
                str(testimonial.text) ||
                'The team delivered a thoughtful renovation experience with strong communication and reliable workmanship.';
              const rating = num(testimonial.rating) ?? 5;
              const source = str(testimonial.source) || 'Google';

              return (
                <StaggerItem key={`${author}-${index}`} className="h-full">
                  <article className={`${CARD} h-full border border-stone-200/80 p-6`}>
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex items-center gap-4">
                        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-stone-100 font-heading text-lg font-bold text-stone-900">
                          {initials(author)}
                        </div>
                        <div>
                          <p className="font-heading text-xl font-bold text-stone-900">{author}</p>
                          <p className="font-body text-xs uppercase tracking-[0.18em] text-primary">{source}</p>
                        </div>
                      </div>
                      <p className="font-body text-sm font-semibold tracking-[0.12em] text-primary">
                        {stars(rating)}
                      </p>
                    </div>
                    <p className="mt-6 font-body text-sm leading-7 text-stone-600">“{text}”</p>
                  </article>
                </StaggerItem>
              );
            })}
          </div>
        </StaggerContainer>
      </div>
    </section>
  );
}

export function OurProcess({ branding, config, tokens, className }: SectionBaseProps) {
  const steps = contentArray<Record<string, unknown>>('processSteps');

  return (
    <section className={`${SECTION} bg-stone-50 text-stone-900 ${className ?? ''}`}>
      <div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10 xl:px-14">
        <FadeInUp>
          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-3xl">
              <SectionEyebrow>Our Process</SectionEyebrow>
              <h2 className="mt-5 font-heading text-3xl font-bold leading-tight text-stone-900 sm:text-4xl md:text-5xl">
                A process built to keep scope, design intent, and execution aligned.
              </h2>
            </div>
            <p className="max-w-xl font-body text-base leading-7 text-stone-600">
              Design-build works best when each phase carries forward the same priorities. These
              steps keep momentum without losing the details that matter.
            </p>
          </div>
        </FadeInUp>

        <StaggerContainer className="mt-12 grid gap-6 lg:grid-cols-4">
          {(steps.length
            ? steps
            : [
                { title: 'Consultation', description: 'Discuss your renovation needs and ideas.' },
                { title: 'Design Phase', description: 'Our team creates tailored designs.' },
                { title: 'Construction', description: 'Our skilled team brings your project to life.' },
                { title: 'Final Walkthrough', description: 'Ensure everything meets your expectations.' },
              ]
          ).map((step, index) => {
            const title = str(step.title) || `Step ${index + 1}`;
            const description = str(step.description) || 'A clear milestone in the renovation journey.';

            return (
              <StaggerItem key={`${title}-${index}`}>
                <article className={`${CARD} relative h-full border border-stone-200/80 p-6 pt-20`}>
                  <div className="absolute left-6 top-6 flex h-12 w-12 items-center justify-center rounded-full bg-primary font-heading text-lg font-bold text-white">
                    {index + 1}
                  </div>
                  <SectionEyebrow>{title}</SectionEyebrow>
                  <h3 className="mt-4 font-heading text-2xl font-bold text-stone-900">{title}</h3>
                  <p className="mt-3 font-body text-sm leading-6 text-stone-600">{description}</p>
                  <div className="mt-6 h-px w-full bg-stone-200" />
                  <p className="mt-5 font-body text-xs uppercase tracking-[0.18em] text-stone-500">
                    Step {index + 1} of 4
                  </p>
                </article>
              </StaggerItem>
            );
          })}
        </StaggerContainer>

        <FadeInUp>
          <div className="mt-10 rounded-[32px] bg-primary p-8 text-white shadow-[0_18px_44px_rgba(107,104,84,0.24)]">
            <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center">
              <div>
                <SectionEyebrow>How It Works</SectionEyebrow>
                <h3 className="mt-4 font-heading text-3xl font-bold leading-tight">
                  Upload a photo, explore directions, then turn concept into a real build plan.
                </h3>
                <p className="mt-4 max-w-2xl font-body text-sm leading-6 text-white/82">
                  The design studio gives homeowners a quick way to compare ideas, gather visual
                  clarity, and move into consultation with a stronger brief.
                </p>
              </div>
              <div className="flex flex-col gap-3 sm:flex-row lg:flex-col">
                <Link href="/visualizer">
                  <span className="inline-flex items-center justify-center rounded-full bg-white px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-stone-900 transition duration-300 hover:scale-[1.02] hover:bg-stone-100">
                    See Your Space Before You Build
                  </span>
                </Link>
                <Link href="/visualizer?mode=chat">
                  <span className="inline-flex items-center justify-center rounded-full border border-white/40 px-6 py-3 font-body text-sm font-semibold uppercase tracking-[0.18em] text-white transition duration-300 hover:scale-[1.02] hover:bg-white/12">
                    Get a Quick Estimate
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </FadeInUp>
      </div>
    </section>
  );
}

export function WhyChooseUs({ branding, config, tokens, className }: SectionBaseProps) {
  const metrics = [
    {
      label: 'Design-Build Delivery',
      value: 'One team',
      description: 'Planning, permits, project management, and construction stay under one roof.',
    },
    {
      label: 'Regional Focus',
      value: contentArray<string>('serviceAreas').length
        ? `${contentArray<string>('serviceAreas').length} Cities`
        : '4 Cities',
      description: 'Serving homeowners across Kitchener, Waterloo, Cambridge, and Guelph.',
    },
    {
      label: 'Craft Priority',
      value: 'Detail-led',
      description: 'Clean finishes, practical layouts, and materials chosen for everyday use.',
    },
  ];

  const trustPanels = [
    {
      title: 'Design intelligence',
      text: 'Interior design support keeps layout, materials, and final feel aligned from day one.',
    },
    {
      title: 'Project control',
      text: 'Project managers keep sequencing, coordination, and homeowner communication in view.',
    },
    {
      title: 'Skilled execution',
      text: 'Experienced builders turn approved plans into finished spaces without losing the details.',
    },
  ];

  const stats = [
    {
      label: 'Years in business',
      value: metricValue('yearsInBusiness') ? `${metricValue('yearsInBusiness')}+` : '10',
    },
    {
      label: 'Projects completed',
      value: metricValue('projectsCompleted') ? `${metricValue('projectsCompleted')}+` : '100+',
    },
    {
      label: 'Google rating',
      value: metricValue('googleRating') ? `${metricValue('googleRating')}` : '5.0',
    },
  ];

  return (
    <section className={`${SECTION} bg-stone-950 text-white ${className ?? ''}`}>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(107,104,84,0.24),transparent_26%),radial-gradient(circle_at_bottom_left,rgba(255,255,255,0.06),transparent_20%)]" />
      <div className="relative mx-auto max-w-7xl px-6 sm:px-8 lg:px-10 xl:px-14">
        <FadeInUp>
          <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end">
            <div className="max-w-3xl">
              <SectionEyebrow>Why Choose Us</SectionEyebrow>
              <h2 className="mt-5 font-heading text-3xl font-bold leading-tight text-white sm:text-4xl md:text-5xl">
                Why homeowners choose a team that can think like designers and build like pros.
              </h2>
              <p className="mt-5 max-w-2xl font-body text-base leading-7 text-white/76 sm:text-lg">
                Renovations become calmer when the same group owns the vision, the details, and the
                responsibility to get it built properly.
              </p>
            </div>
            <div className="grid grid-cols-3 gap-3">
              {stats.map((stat) => (
                <div key={stat.label} className="rounded-[24px] border border-white/10 bg-white/6 p-4 text-center backdrop-blur-sm">
                  <p className="font-heading text-3xl font-bold text-white">{stat.value}</p>
                  <p className="mt-2 font-body text-[11px] uppercase tracking-[0.18em] text-white/62">
                    {stat.label}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </FadeInUp>

        <StaggerContainer className="mt-12 grid gap-6 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)]">
          <div className="grid gap-6 md:grid-cols-3">
            {metrics.map((metric) => (
              <StaggerItem key={metric.label}>
                <article className="h-full rounded-[28px] border border-white/10 bg-white/6 p-6 backdrop-blur-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_24px_56px_rgba(0,0,0,0.22)]">
                  <SectionEyebrow>{metric.label}</SectionEyebrow>
                  <p className="mt-4 font-heading text-3xl font-bold text-white">{metric.value}</p>
                  <p className="mt-4 font-body text-sm leading-6 text-white/74">{metric.description}</p>
                </article>
              </StaggerItem>
            ))}
          </div>

          <StaggerItem>
            <div className="rounded-[32px] bg-white p-5 text-stone-900 shadow-[0_18px_44px_rgba(15,23,42,0.14)]">
              <div className="grid gap-4">
                {trustPanels.map((panel) => (
                  <div key={panel.title} className={`${CARD} border border-stone-200/80 p-6`}>
                    <SectionEyebrow>{panel.title}</SectionEyebrow>
                    <h3 className="mt-4 font-heading text-2xl font-bold text-stone-900">{panel.title}</h3>
                    <p className="mt-3 font-body text-sm leading-6 text-stone-600">{panel.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </StaggerItem>
        </StaggerContainer>
      </div>
    </section>
  );
}

