/**
 * Sprint 3 Contracts — Dominant Builder
 * Type definitions for the Opus Vision blueprint generation pipeline.
 *
 * SectionId uses the same "category:variant" pattern as the section registry.
 * e.g. "hero:full-bleed-overlay", "services:grid-3-cards"
 */

/** Matches the section registry pattern */
type SectionId = `${string}:${string}`;

/** Design system bundle extracted from original website screenshots */
interface DesignSystemBundle {
  colours: {
    primary: string;       // OKLCH value
    primaryHex: string;    // Hex fallback
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
    muted: string;
  };
  typography: {
    headingFont: string;
    bodyFont: string;
    headingWeight: string;
    bodyWeight: string;
    headingSize: {
      h1: string;
      h2: string;
      h3: string;
    };
  };
  spacing: {
    sectionPadding: string;
    contentMaxWidth: string;
    cardGap: string;
  };
  borders: {
    radius: string;
    width: string;
  };
  shadows: {
    card: string;
    elevated: string;
  };
  pages: string[];           // URLs of scraped pages
  navigation: {
    style: 'sticky' | 'fixed' | 'relative';
    items: string[];
  };
  footer: {
    columnCount: number;
    style: 'minimal' | 'detailed';
  };
}

/** Blueprint for a single page */
interface PageBlueprint {
  slug: string;              // e.g. "homepage", "about", "services"
  title: string;
  sections: {
    componentId: SectionId | 'CUSTOM';
    props: Record<string, unknown>;
    customSpec?: string;       // Markdown spec for CUSTOM sections
    animationPreset: 'fade-in-up' | 'stagger-reveal' | 'slide-in-left' | 'none';
  }[];
}

/** Full site blueprint generated by Opus Vision */
interface SiteBlueprintV2 {
  version: '2.0';
  tenant: string;            // site_id
  generatedAt: string;       // ISO timestamp
  designSystem: DesignSystemBundle;
  pages: PageBlueprint[];
  navigation: {
    componentId: SectionId;
    links: { label: string; href: string }[];
  };
  footer: {
    componentId: SectionId;
    columns: { heading: string; links: { label: string; href: string }[] }[];
  };
  platformIntegration: PlatformEmbedContract;
  complexityScore: number;     // 1-10
  customSectionCount: number;  // 0-3 enforced
}

/** Which platform features to embed on which pages */
interface PlatformEmbedContract {
  visualizer: { enabled: boolean; pages: string[] };
  emma_chat: { enabled: boolean; pages: string[] };
  quote_engine: { enabled: boolean; pages: string[] };
  voice_agent: { enabled: boolean; pages: string[] };
}

export type {
  SectionId,
  DesignSystemBundle,
  PageBlueprint,
  SiteBlueprintV2,
  PlatformEmbedContract,
};
